// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package cloudcontrol

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-alicloud/sdk/v3/go/alicloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type GetPricesPrice struct {
	// Currency. Value range: CNY: RMB. USD: USD. JPY: Japanese yen.
	Currency string `pulumi:"currency"`
	// Discount
	DiscountPrice float64 `pulumi:"discountPrice"`
	// Pricing Module Price Details
	ModuleDetails []GetPricesPriceModuleDetail `pulumi:"moduleDetails"`
	// Original Price
	OriginalPrice float64 `pulumi:"originalPrice"`
	// Offer Details
	PromotionDetails []GetPricesPricePromotionDetail `pulumi:"promotionDetails"`
	// Preferential price
	TradePrice float64 `pulumi:"tradePrice"`
}

// GetPricesPriceInput is an input type that accepts GetPricesPriceArgs and GetPricesPriceOutput values.
// You can construct a concrete instance of `GetPricesPriceInput` via:
//
//	GetPricesPriceArgs{...}
type GetPricesPriceInput interface {
	pulumi.Input

	ToGetPricesPriceOutput() GetPricesPriceOutput
	ToGetPricesPriceOutputWithContext(context.Context) GetPricesPriceOutput
}

type GetPricesPriceArgs struct {
	// Currency. Value range: CNY: RMB. USD: USD. JPY: Japanese yen.
	Currency pulumi.StringInput `pulumi:"currency"`
	// Discount
	DiscountPrice pulumi.Float64Input `pulumi:"discountPrice"`
	// Pricing Module Price Details
	ModuleDetails GetPricesPriceModuleDetailArrayInput `pulumi:"moduleDetails"`
	// Original Price
	OriginalPrice pulumi.Float64Input `pulumi:"originalPrice"`
	// Offer Details
	PromotionDetails GetPricesPricePromotionDetailArrayInput `pulumi:"promotionDetails"`
	// Preferential price
	TradePrice pulumi.Float64Input `pulumi:"tradePrice"`
}

func (GetPricesPriceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPricesPrice)(nil)).Elem()
}

func (i GetPricesPriceArgs) ToGetPricesPriceOutput() GetPricesPriceOutput {
	return i.ToGetPricesPriceOutputWithContext(context.Background())
}

func (i GetPricesPriceArgs) ToGetPricesPriceOutputWithContext(ctx context.Context) GetPricesPriceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPricesPriceOutput)
}

// GetPricesPriceArrayInput is an input type that accepts GetPricesPriceArray and GetPricesPriceArrayOutput values.
// You can construct a concrete instance of `GetPricesPriceArrayInput` via:
//
//	GetPricesPriceArray{ GetPricesPriceArgs{...} }
type GetPricesPriceArrayInput interface {
	pulumi.Input

	ToGetPricesPriceArrayOutput() GetPricesPriceArrayOutput
	ToGetPricesPriceArrayOutputWithContext(context.Context) GetPricesPriceArrayOutput
}

type GetPricesPriceArray []GetPricesPriceInput

func (GetPricesPriceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPricesPrice)(nil)).Elem()
}

func (i GetPricesPriceArray) ToGetPricesPriceArrayOutput() GetPricesPriceArrayOutput {
	return i.ToGetPricesPriceArrayOutputWithContext(context.Background())
}

func (i GetPricesPriceArray) ToGetPricesPriceArrayOutputWithContext(ctx context.Context) GetPricesPriceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPricesPriceArrayOutput)
}

type GetPricesPriceOutput struct{ *pulumi.OutputState }

func (GetPricesPriceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPricesPrice)(nil)).Elem()
}

func (o GetPricesPriceOutput) ToGetPricesPriceOutput() GetPricesPriceOutput {
	return o
}

func (o GetPricesPriceOutput) ToGetPricesPriceOutputWithContext(ctx context.Context) GetPricesPriceOutput {
	return o
}

// Currency. Value range: CNY: RMB. USD: USD. JPY: Japanese yen.
func (o GetPricesPriceOutput) Currency() pulumi.StringOutput {
	return o.ApplyT(func(v GetPricesPrice) string { return v.Currency }).(pulumi.StringOutput)
}

// Discount
func (o GetPricesPriceOutput) DiscountPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetPricesPrice) float64 { return v.DiscountPrice }).(pulumi.Float64Output)
}

// Pricing Module Price Details
func (o GetPricesPriceOutput) ModuleDetails() GetPricesPriceModuleDetailArrayOutput {
	return o.ApplyT(func(v GetPricesPrice) []GetPricesPriceModuleDetail { return v.ModuleDetails }).(GetPricesPriceModuleDetailArrayOutput)
}

// Original Price
func (o GetPricesPriceOutput) OriginalPrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetPricesPrice) float64 { return v.OriginalPrice }).(pulumi.Float64Output)
}

// Offer Details
func (o GetPricesPriceOutput) PromotionDetails() GetPricesPricePromotionDetailArrayOutput {
	return o.ApplyT(func(v GetPricesPrice) []GetPricesPricePromotionDetail { return v.PromotionDetails }).(GetPricesPricePromotionDetailArrayOutput)
}

// Preferential price
func (o GetPricesPriceOutput) TradePrice() pulumi.Float64Output {
	return o.ApplyT(func(v GetPricesPrice) float64 { return v.TradePrice }).(pulumi.Float64Output)
}

type GetPricesPriceArrayOutput struct{ *pulumi.OutputState }

func (GetPricesPriceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPricesPrice)(nil)).Elem()
}

func (o GetPricesPriceArrayOutput) ToGetPricesPriceArrayOutput() GetPricesPriceArrayOutput {
	return o
}

func (o GetPricesPriceArrayOutput) ToGetPricesPriceArrayOutputWithContext(ctx context.Context) GetPricesPriceArrayOutput {
	return o
}

func (o GetPricesPriceArrayOutput) Index(i pulumi.IntInput) GetPricesPriceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPricesPrice {
		return vs[0].([]GetPricesPrice)[vs[1].(int)]
	}).(GetPricesPriceOutput)
}

type GetPricesPriceModuleDetail struct {
	// Preferential price.
	CostAfterDiscount float64 `pulumi:"costAfterDiscount"`
	// Discount.
	InvoiceDiscount float64 `pulumi:"invoiceDiscount"`
	// Valuation Module Identification.
	ModuleCode string `pulumi:"moduleCode"`
	// Pricing Module Name.
	ModuleName string `pulumi:"moduleName"`
	// Original Price.
	OriginalCost float64 `pulumi:"originalCost"`
	// Price Type.
	PriceType string `pulumi:"priceType"`
}

// GetPricesPriceModuleDetailInput is an input type that accepts GetPricesPriceModuleDetailArgs and GetPricesPriceModuleDetailOutput values.
// You can construct a concrete instance of `GetPricesPriceModuleDetailInput` via:
//
//	GetPricesPriceModuleDetailArgs{...}
type GetPricesPriceModuleDetailInput interface {
	pulumi.Input

	ToGetPricesPriceModuleDetailOutput() GetPricesPriceModuleDetailOutput
	ToGetPricesPriceModuleDetailOutputWithContext(context.Context) GetPricesPriceModuleDetailOutput
}

type GetPricesPriceModuleDetailArgs struct {
	// Preferential price.
	CostAfterDiscount pulumi.Float64Input `pulumi:"costAfterDiscount"`
	// Discount.
	InvoiceDiscount pulumi.Float64Input `pulumi:"invoiceDiscount"`
	// Valuation Module Identification.
	ModuleCode pulumi.StringInput `pulumi:"moduleCode"`
	// Pricing Module Name.
	ModuleName pulumi.StringInput `pulumi:"moduleName"`
	// Original Price.
	OriginalCost pulumi.Float64Input `pulumi:"originalCost"`
	// Price Type.
	PriceType pulumi.StringInput `pulumi:"priceType"`
}

func (GetPricesPriceModuleDetailArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPricesPriceModuleDetail)(nil)).Elem()
}

func (i GetPricesPriceModuleDetailArgs) ToGetPricesPriceModuleDetailOutput() GetPricesPriceModuleDetailOutput {
	return i.ToGetPricesPriceModuleDetailOutputWithContext(context.Background())
}

func (i GetPricesPriceModuleDetailArgs) ToGetPricesPriceModuleDetailOutputWithContext(ctx context.Context) GetPricesPriceModuleDetailOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPricesPriceModuleDetailOutput)
}

// GetPricesPriceModuleDetailArrayInput is an input type that accepts GetPricesPriceModuleDetailArray and GetPricesPriceModuleDetailArrayOutput values.
// You can construct a concrete instance of `GetPricesPriceModuleDetailArrayInput` via:
//
//	GetPricesPriceModuleDetailArray{ GetPricesPriceModuleDetailArgs{...} }
type GetPricesPriceModuleDetailArrayInput interface {
	pulumi.Input

	ToGetPricesPriceModuleDetailArrayOutput() GetPricesPriceModuleDetailArrayOutput
	ToGetPricesPriceModuleDetailArrayOutputWithContext(context.Context) GetPricesPriceModuleDetailArrayOutput
}

type GetPricesPriceModuleDetailArray []GetPricesPriceModuleDetailInput

func (GetPricesPriceModuleDetailArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPricesPriceModuleDetail)(nil)).Elem()
}

func (i GetPricesPriceModuleDetailArray) ToGetPricesPriceModuleDetailArrayOutput() GetPricesPriceModuleDetailArrayOutput {
	return i.ToGetPricesPriceModuleDetailArrayOutputWithContext(context.Background())
}

func (i GetPricesPriceModuleDetailArray) ToGetPricesPriceModuleDetailArrayOutputWithContext(ctx context.Context) GetPricesPriceModuleDetailArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPricesPriceModuleDetailArrayOutput)
}

type GetPricesPriceModuleDetailOutput struct{ *pulumi.OutputState }

func (GetPricesPriceModuleDetailOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPricesPriceModuleDetail)(nil)).Elem()
}

func (o GetPricesPriceModuleDetailOutput) ToGetPricesPriceModuleDetailOutput() GetPricesPriceModuleDetailOutput {
	return o
}

func (o GetPricesPriceModuleDetailOutput) ToGetPricesPriceModuleDetailOutputWithContext(ctx context.Context) GetPricesPriceModuleDetailOutput {
	return o
}

// Preferential price.
func (o GetPricesPriceModuleDetailOutput) CostAfterDiscount() pulumi.Float64Output {
	return o.ApplyT(func(v GetPricesPriceModuleDetail) float64 { return v.CostAfterDiscount }).(pulumi.Float64Output)
}

// Discount.
func (o GetPricesPriceModuleDetailOutput) InvoiceDiscount() pulumi.Float64Output {
	return o.ApplyT(func(v GetPricesPriceModuleDetail) float64 { return v.InvoiceDiscount }).(pulumi.Float64Output)
}

// Valuation Module Identification.
func (o GetPricesPriceModuleDetailOutput) ModuleCode() pulumi.StringOutput {
	return o.ApplyT(func(v GetPricesPriceModuleDetail) string { return v.ModuleCode }).(pulumi.StringOutput)
}

// Pricing Module Name.
func (o GetPricesPriceModuleDetailOutput) ModuleName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPricesPriceModuleDetail) string { return v.ModuleName }).(pulumi.StringOutput)
}

// Original Price.
func (o GetPricesPriceModuleDetailOutput) OriginalCost() pulumi.Float64Output {
	return o.ApplyT(func(v GetPricesPriceModuleDetail) float64 { return v.OriginalCost }).(pulumi.Float64Output)
}

// Price Type.
func (o GetPricesPriceModuleDetailOutput) PriceType() pulumi.StringOutput {
	return o.ApplyT(func(v GetPricesPriceModuleDetail) string { return v.PriceType }).(pulumi.StringOutput)
}

type GetPricesPriceModuleDetailArrayOutput struct{ *pulumi.OutputState }

func (GetPricesPriceModuleDetailArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPricesPriceModuleDetail)(nil)).Elem()
}

func (o GetPricesPriceModuleDetailArrayOutput) ToGetPricesPriceModuleDetailArrayOutput() GetPricesPriceModuleDetailArrayOutput {
	return o
}

func (o GetPricesPriceModuleDetailArrayOutput) ToGetPricesPriceModuleDetailArrayOutputWithContext(ctx context.Context) GetPricesPriceModuleDetailArrayOutput {
	return o
}

func (o GetPricesPriceModuleDetailArrayOutput) Index(i pulumi.IntInput) GetPricesPriceModuleDetailOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPricesPriceModuleDetail {
		return vs[0].([]GetPricesPriceModuleDetail)[vs[1].(int)]
	}).(GetPricesPriceModuleDetailOutput)
}

type GetPricesPricePromotionDetail struct {
	// Offer Description.
	PromotionDesc string `pulumi:"promotionDesc"`
	// Offer logo.
	PromotionId int `pulumi:"promotionId"`
	// Offer Name.
	PromotionName string `pulumi:"promotionName"`
}

// GetPricesPricePromotionDetailInput is an input type that accepts GetPricesPricePromotionDetailArgs and GetPricesPricePromotionDetailOutput values.
// You can construct a concrete instance of `GetPricesPricePromotionDetailInput` via:
//
//	GetPricesPricePromotionDetailArgs{...}
type GetPricesPricePromotionDetailInput interface {
	pulumi.Input

	ToGetPricesPricePromotionDetailOutput() GetPricesPricePromotionDetailOutput
	ToGetPricesPricePromotionDetailOutputWithContext(context.Context) GetPricesPricePromotionDetailOutput
}

type GetPricesPricePromotionDetailArgs struct {
	// Offer Description.
	PromotionDesc pulumi.StringInput `pulumi:"promotionDesc"`
	// Offer logo.
	PromotionId pulumi.IntInput `pulumi:"promotionId"`
	// Offer Name.
	PromotionName pulumi.StringInput `pulumi:"promotionName"`
}

func (GetPricesPricePromotionDetailArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPricesPricePromotionDetail)(nil)).Elem()
}

func (i GetPricesPricePromotionDetailArgs) ToGetPricesPricePromotionDetailOutput() GetPricesPricePromotionDetailOutput {
	return i.ToGetPricesPricePromotionDetailOutputWithContext(context.Background())
}

func (i GetPricesPricePromotionDetailArgs) ToGetPricesPricePromotionDetailOutputWithContext(ctx context.Context) GetPricesPricePromotionDetailOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPricesPricePromotionDetailOutput)
}

// GetPricesPricePromotionDetailArrayInput is an input type that accepts GetPricesPricePromotionDetailArray and GetPricesPricePromotionDetailArrayOutput values.
// You can construct a concrete instance of `GetPricesPricePromotionDetailArrayInput` via:
//
//	GetPricesPricePromotionDetailArray{ GetPricesPricePromotionDetailArgs{...} }
type GetPricesPricePromotionDetailArrayInput interface {
	pulumi.Input

	ToGetPricesPricePromotionDetailArrayOutput() GetPricesPricePromotionDetailArrayOutput
	ToGetPricesPricePromotionDetailArrayOutputWithContext(context.Context) GetPricesPricePromotionDetailArrayOutput
}

type GetPricesPricePromotionDetailArray []GetPricesPricePromotionDetailInput

func (GetPricesPricePromotionDetailArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPricesPricePromotionDetail)(nil)).Elem()
}

func (i GetPricesPricePromotionDetailArray) ToGetPricesPricePromotionDetailArrayOutput() GetPricesPricePromotionDetailArrayOutput {
	return i.ToGetPricesPricePromotionDetailArrayOutputWithContext(context.Background())
}

func (i GetPricesPricePromotionDetailArray) ToGetPricesPricePromotionDetailArrayOutputWithContext(ctx context.Context) GetPricesPricePromotionDetailArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetPricesPricePromotionDetailArrayOutput)
}

type GetPricesPricePromotionDetailOutput struct{ *pulumi.OutputState }

func (GetPricesPricePromotionDetailOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPricesPricePromotionDetail)(nil)).Elem()
}

func (o GetPricesPricePromotionDetailOutput) ToGetPricesPricePromotionDetailOutput() GetPricesPricePromotionDetailOutput {
	return o
}

func (o GetPricesPricePromotionDetailOutput) ToGetPricesPricePromotionDetailOutputWithContext(ctx context.Context) GetPricesPricePromotionDetailOutput {
	return o
}

// Offer Description.
func (o GetPricesPricePromotionDetailOutput) PromotionDesc() pulumi.StringOutput {
	return o.ApplyT(func(v GetPricesPricePromotionDetail) string { return v.PromotionDesc }).(pulumi.StringOutput)
}

// Offer logo.
func (o GetPricesPricePromotionDetailOutput) PromotionId() pulumi.IntOutput {
	return o.ApplyT(func(v GetPricesPricePromotionDetail) int { return v.PromotionId }).(pulumi.IntOutput)
}

// Offer Name.
func (o GetPricesPricePromotionDetailOutput) PromotionName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPricesPricePromotionDetail) string { return v.PromotionName }).(pulumi.StringOutput)
}

type GetPricesPricePromotionDetailArrayOutput struct{ *pulumi.OutputState }

func (GetPricesPricePromotionDetailArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetPricesPricePromotionDetail)(nil)).Elem()
}

func (o GetPricesPricePromotionDetailArrayOutput) ToGetPricesPricePromotionDetailArrayOutput() GetPricesPricePromotionDetailArrayOutput {
	return o
}

func (o GetPricesPricePromotionDetailArrayOutput) ToGetPricesPricePromotionDetailArrayOutputWithContext(ctx context.Context) GetPricesPricePromotionDetailArrayOutput {
	return o
}

func (o GetPricesPricePromotionDetailArrayOutput) Index(i pulumi.IntInput) GetPricesPricePromotionDetailOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetPricesPricePromotionDetail {
		return vs[0].([]GetPricesPricePromotionDetail)[vs[1].(int)]
	}).(GetPricesPricePromotionDetailOutput)
}

type GetProductsProduct struct {
	// The ID of the resource supplied above.
	Id string `pulumi:"id"`
	// The first ID of the resource
	ProductCode string `pulumi:"productCode"`
	// The name of the resource
	ProductName string `pulumi:"productName"`
}

// GetProductsProductInput is an input type that accepts GetProductsProductArgs and GetProductsProductOutput values.
// You can construct a concrete instance of `GetProductsProductInput` via:
//
//	GetProductsProductArgs{...}
type GetProductsProductInput interface {
	pulumi.Input

	ToGetProductsProductOutput() GetProductsProductOutput
	ToGetProductsProductOutputWithContext(context.Context) GetProductsProductOutput
}

type GetProductsProductArgs struct {
	// The ID of the resource supplied above.
	Id pulumi.StringInput `pulumi:"id"`
	// The first ID of the resource
	ProductCode pulumi.StringInput `pulumi:"productCode"`
	// The name of the resource
	ProductName pulumi.StringInput `pulumi:"productName"`
}

func (GetProductsProductArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductsProduct)(nil)).Elem()
}

func (i GetProductsProductArgs) ToGetProductsProductOutput() GetProductsProductOutput {
	return i.ToGetProductsProductOutputWithContext(context.Background())
}

func (i GetProductsProductArgs) ToGetProductsProductOutputWithContext(ctx context.Context) GetProductsProductOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetProductsProductOutput)
}

// GetProductsProductArrayInput is an input type that accepts GetProductsProductArray and GetProductsProductArrayOutput values.
// You can construct a concrete instance of `GetProductsProductArrayInput` via:
//
//	GetProductsProductArray{ GetProductsProductArgs{...} }
type GetProductsProductArrayInput interface {
	pulumi.Input

	ToGetProductsProductArrayOutput() GetProductsProductArrayOutput
	ToGetProductsProductArrayOutputWithContext(context.Context) GetProductsProductArrayOutput
}

type GetProductsProductArray []GetProductsProductInput

func (GetProductsProductArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetProductsProduct)(nil)).Elem()
}

func (i GetProductsProductArray) ToGetProductsProductArrayOutput() GetProductsProductArrayOutput {
	return i.ToGetProductsProductArrayOutputWithContext(context.Background())
}

func (i GetProductsProductArray) ToGetProductsProductArrayOutputWithContext(ctx context.Context) GetProductsProductArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetProductsProductArrayOutput)
}

type GetProductsProductOutput struct{ *pulumi.OutputState }

func (GetProductsProductOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetProductsProduct)(nil)).Elem()
}

func (o GetProductsProductOutput) ToGetProductsProductOutput() GetProductsProductOutput {
	return o
}

func (o GetProductsProductOutput) ToGetProductsProductOutputWithContext(ctx context.Context) GetProductsProductOutput {
	return o
}

// The ID of the resource supplied above.
func (o GetProductsProductOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductsProduct) string { return v.Id }).(pulumi.StringOutput)
}

// The first ID of the resource
func (o GetProductsProductOutput) ProductCode() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductsProduct) string { return v.ProductCode }).(pulumi.StringOutput)
}

// The name of the resource
func (o GetProductsProductOutput) ProductName() pulumi.StringOutput {
	return o.ApplyT(func(v GetProductsProduct) string { return v.ProductName }).(pulumi.StringOutput)
}

type GetProductsProductArrayOutput struct{ *pulumi.OutputState }

func (GetProductsProductArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetProductsProduct)(nil)).Elem()
}

func (o GetProductsProductArrayOutput) ToGetProductsProductArrayOutput() GetProductsProductArrayOutput {
	return o
}

func (o GetProductsProductArrayOutput) ToGetProductsProductArrayOutputWithContext(ctx context.Context) GetProductsProductArrayOutput {
	return o
}

func (o GetProductsProductArrayOutput) Index(i pulumi.IntInput) GetProductsProductOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetProductsProduct {
		return vs[0].([]GetProductsProduct)[vs[1].(int)]
	}).(GetProductsProductOutput)
}

type GetResourceTypesType struct {
	// Create an operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters are required in the creation operation.
	CreateOnlyProperties []string `pulumi:"createOnlyProperties"`
	// Delete operation private parameter collection. The attribute is not returned in the resource query operation, but the parameter is required in the delete operation.
	DeleteOnlyProperties []string `pulumi:"deleteOnlyProperties"`
	// A collection of attributes that can be used as the filter parameter during the list operation.
	FilterProperties []string `pulumi:"filterProperties"`
	// Query operation private parameter collection. The attribute is not returned in the resource query operation, but the input parameter is required in the query operation.
	GetOnlyProperties []string `pulumi:"getOnlyProperties"`
	// The collection of properties returned by the query.
	GetResponseProperties []string `pulumi:"getResponseProperties"`
	// Supported resource operation information (including RAM permissions).
	Handlers GetResourceTypesTypeHandlers `pulumi:"handlers"`
	// The ID of the resource supplied above.
	Id string `pulumi:"id"`
	// Basic information about the resource type.
	Infos []GetResourceTypesTypeInfo `pulumi:"infos"`
	// Enumerate the operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters that need to be passed in the enumeration operation.
	ListOnlyProperties []string `pulumi:"listOnlyProperties"`
	// Enumerates the returned property collection.
	ListResponseProperties []string `pulumi:"listResponseProperties"`
	// Resource ID
	PrimaryIdentifier string `pulumi:"primaryIdentifier"`
	// Product Code.
	Product string `pulumi:"product"`
	// Resource attribute definition, where key is the attribute name and value is the attribute details.
	Properties string `pulumi:"properties"`
	// A collection of public attributes, which are the basic attributes of the resource. Non-Operation private parameters.
	PublicProperties []string `pulumi:"publicProperties"`
	// A set of read-only parameters. It is returned only in the list or get Operation. It is not used as an input parameter during creation and change.
	ReadOnlyProperties []string `pulumi:"readOnlyProperties"`
	// Resource creation required parameter collection.
	Requireds []string `pulumi:"requireds"`
	// The resource type.
	ResourceType string `pulumi:"resourceType"`
	// A collection of sensitive attributes, such as passwords.
	SensitiveInfoProperties []string `pulumi:"sensitiveInfoProperties"`
	// Update operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters are required in the update operation.
	UpdateOnlyProperties []string `pulumi:"updateOnlyProperties"`
	// A collection of properties that can be modified.
	UpdateTypeProperties []string `pulumi:"updateTypeProperties"`
}

// GetResourceTypesTypeInput is an input type that accepts GetResourceTypesTypeArgs and GetResourceTypesTypeOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeInput` via:
//
//	GetResourceTypesTypeArgs{...}
type GetResourceTypesTypeInput interface {
	pulumi.Input

	ToGetResourceTypesTypeOutput() GetResourceTypesTypeOutput
	ToGetResourceTypesTypeOutputWithContext(context.Context) GetResourceTypesTypeOutput
}

type GetResourceTypesTypeArgs struct {
	// Create an operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters are required in the creation operation.
	CreateOnlyProperties pulumi.StringArrayInput `pulumi:"createOnlyProperties"`
	// Delete operation private parameter collection. The attribute is not returned in the resource query operation, but the parameter is required in the delete operation.
	DeleteOnlyProperties pulumi.StringArrayInput `pulumi:"deleteOnlyProperties"`
	// A collection of attributes that can be used as the filter parameter during the list operation.
	FilterProperties pulumi.StringArrayInput `pulumi:"filterProperties"`
	// Query operation private parameter collection. The attribute is not returned in the resource query operation, but the input parameter is required in the query operation.
	GetOnlyProperties pulumi.StringArrayInput `pulumi:"getOnlyProperties"`
	// The collection of properties returned by the query.
	GetResponseProperties pulumi.StringArrayInput `pulumi:"getResponseProperties"`
	// Supported resource operation information (including RAM permissions).
	Handlers GetResourceTypesTypeHandlersInput `pulumi:"handlers"`
	// The ID of the resource supplied above.
	Id pulumi.StringInput `pulumi:"id"`
	// Basic information about the resource type.
	Infos GetResourceTypesTypeInfoArrayInput `pulumi:"infos"`
	// Enumerate the operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters that need to be passed in the enumeration operation.
	ListOnlyProperties pulumi.StringArrayInput `pulumi:"listOnlyProperties"`
	// Enumerates the returned property collection.
	ListResponseProperties pulumi.StringArrayInput `pulumi:"listResponseProperties"`
	// Resource ID
	PrimaryIdentifier pulumi.StringInput `pulumi:"primaryIdentifier"`
	// Product Code.
	Product pulumi.StringInput `pulumi:"product"`
	// Resource attribute definition, where key is the attribute name and value is the attribute details.
	Properties pulumi.StringInput `pulumi:"properties"`
	// A collection of public attributes, which are the basic attributes of the resource. Non-Operation private parameters.
	PublicProperties pulumi.StringArrayInput `pulumi:"publicProperties"`
	// A set of read-only parameters. It is returned only in the list or get Operation. It is not used as an input parameter during creation and change.
	ReadOnlyProperties pulumi.StringArrayInput `pulumi:"readOnlyProperties"`
	// Resource creation required parameter collection.
	Requireds pulumi.StringArrayInput `pulumi:"requireds"`
	// The resource type.
	ResourceType pulumi.StringInput `pulumi:"resourceType"`
	// A collection of sensitive attributes, such as passwords.
	SensitiveInfoProperties pulumi.StringArrayInput `pulumi:"sensitiveInfoProperties"`
	// Update operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters are required in the update operation.
	UpdateOnlyProperties pulumi.StringArrayInput `pulumi:"updateOnlyProperties"`
	// A collection of properties that can be modified.
	UpdateTypeProperties pulumi.StringArrayInput `pulumi:"updateTypeProperties"`
}

func (GetResourceTypesTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesType)(nil)).Elem()
}

func (i GetResourceTypesTypeArgs) ToGetResourceTypesTypeOutput() GetResourceTypesTypeOutput {
	return i.ToGetResourceTypesTypeOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeArgs) ToGetResourceTypesTypeOutputWithContext(ctx context.Context) GetResourceTypesTypeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeOutput)
}

// GetResourceTypesTypeArrayInput is an input type that accepts GetResourceTypesTypeArray and GetResourceTypesTypeArrayOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeArrayInput` via:
//
//	GetResourceTypesTypeArray{ GetResourceTypesTypeArgs{...} }
type GetResourceTypesTypeArrayInput interface {
	pulumi.Input

	ToGetResourceTypesTypeArrayOutput() GetResourceTypesTypeArrayOutput
	ToGetResourceTypesTypeArrayOutputWithContext(context.Context) GetResourceTypesTypeArrayOutput
}

type GetResourceTypesTypeArray []GetResourceTypesTypeInput

func (GetResourceTypesTypeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesType)(nil)).Elem()
}

func (i GetResourceTypesTypeArray) ToGetResourceTypesTypeArrayOutput() GetResourceTypesTypeArrayOutput {
	return i.ToGetResourceTypesTypeArrayOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeArray) ToGetResourceTypesTypeArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeArrayOutput)
}

type GetResourceTypesTypeOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesType)(nil)).Elem()
}

func (o GetResourceTypesTypeOutput) ToGetResourceTypesTypeOutput() GetResourceTypesTypeOutput {
	return o
}

func (o GetResourceTypesTypeOutput) ToGetResourceTypesTypeOutputWithContext(ctx context.Context) GetResourceTypesTypeOutput {
	return o
}

// Create an operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters are required in the creation operation.
func (o GetResourceTypesTypeOutput) CreateOnlyProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.CreateOnlyProperties }).(pulumi.StringArrayOutput)
}

// Delete operation private parameter collection. The attribute is not returned in the resource query operation, but the parameter is required in the delete operation.
func (o GetResourceTypesTypeOutput) DeleteOnlyProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.DeleteOnlyProperties }).(pulumi.StringArrayOutput)
}

// A collection of attributes that can be used as the filter parameter during the list operation.
func (o GetResourceTypesTypeOutput) FilterProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.FilterProperties }).(pulumi.StringArrayOutput)
}

// Query operation private parameter collection. The attribute is not returned in the resource query operation, but the input parameter is required in the query operation.
func (o GetResourceTypesTypeOutput) GetOnlyProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.GetOnlyProperties }).(pulumi.StringArrayOutput)
}

// The collection of properties returned by the query.
func (o GetResourceTypesTypeOutput) GetResponseProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.GetResponseProperties }).(pulumi.StringArrayOutput)
}

// Supported resource operation information (including RAM permissions).
func (o GetResourceTypesTypeOutput) Handlers() GetResourceTypesTypeHandlersOutput {
	return o.ApplyT(func(v GetResourceTypesType) GetResourceTypesTypeHandlers { return v.Handlers }).(GetResourceTypesTypeHandlersOutput)
}

// The ID of the resource supplied above.
func (o GetResourceTypesTypeOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesType) string { return v.Id }).(pulumi.StringOutput)
}

// Basic information about the resource type.
func (o GetResourceTypesTypeOutput) Infos() GetResourceTypesTypeInfoArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []GetResourceTypesTypeInfo { return v.Infos }).(GetResourceTypesTypeInfoArrayOutput)
}

// Enumerate the operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters that need to be passed in the enumeration operation.
func (o GetResourceTypesTypeOutput) ListOnlyProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.ListOnlyProperties }).(pulumi.StringArrayOutput)
}

// Enumerates the returned property collection.
func (o GetResourceTypesTypeOutput) ListResponseProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.ListResponseProperties }).(pulumi.StringArrayOutput)
}

// Resource ID
func (o GetResourceTypesTypeOutput) PrimaryIdentifier() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesType) string { return v.PrimaryIdentifier }).(pulumi.StringOutput)
}

// Product Code.
func (o GetResourceTypesTypeOutput) Product() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesType) string { return v.Product }).(pulumi.StringOutput)
}

// Resource attribute definition, where key is the attribute name and value is the attribute details.
func (o GetResourceTypesTypeOutput) Properties() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesType) string { return v.Properties }).(pulumi.StringOutput)
}

// A collection of public attributes, which are the basic attributes of the resource. Non-Operation private parameters.
func (o GetResourceTypesTypeOutput) PublicProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.PublicProperties }).(pulumi.StringArrayOutput)
}

// A set of read-only parameters. It is returned only in the list or get Operation. It is not used as an input parameter during creation and change.
func (o GetResourceTypesTypeOutput) ReadOnlyProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.ReadOnlyProperties }).(pulumi.StringArrayOutput)
}

// Resource creation required parameter collection.
func (o GetResourceTypesTypeOutput) Requireds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.Requireds }).(pulumi.StringArrayOutput)
}

// The resource type.
func (o GetResourceTypesTypeOutput) ResourceType() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesType) string { return v.ResourceType }).(pulumi.StringOutput)
}

// A collection of sensitive attributes, such as passwords.
func (o GetResourceTypesTypeOutput) SensitiveInfoProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.SensitiveInfoProperties }).(pulumi.StringArrayOutput)
}

// Update operation private parameter collection. The attributes are not returned in the resource query operation, but the parameters are required in the update operation.
func (o GetResourceTypesTypeOutput) UpdateOnlyProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.UpdateOnlyProperties }).(pulumi.StringArrayOutput)
}

// A collection of properties that can be modified.
func (o GetResourceTypesTypeOutput) UpdateTypeProperties() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesType) []string { return v.UpdateTypeProperties }).(pulumi.StringArrayOutput)
}

type GetResourceTypesTypeArrayOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesType)(nil)).Elem()
}

func (o GetResourceTypesTypeArrayOutput) ToGetResourceTypesTypeArrayOutput() GetResourceTypesTypeArrayOutput {
	return o
}

func (o GetResourceTypesTypeArrayOutput) ToGetResourceTypesTypeArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeArrayOutput {
	return o
}

func (o GetResourceTypesTypeArrayOutput) Index(i pulumi.IntInput) GetResourceTypesTypeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetResourceTypesType {
		return vs[0].([]GetResourceTypesType)[vs[1].(int)]
	}).(GetResourceTypesTypeOutput)
}

type GetResourceTypesTypeHandlers struct {
	// Create operation association information.
	Creates []GetResourceTypesTypeHandlersCreate `pulumi:"creates"`
	// Delete operation association information.
	Deletes []GetResourceTypesTypeHandlersDelete `pulumi:"deletes"`
	// Query operation association information.
	Gets []GetResourceTypesTypeHandlersGet `pulumi:"gets"`
	// List operation association information.
	Lists []GetResourceTypesTypeHandlersList `pulumi:"lists"`
	// Update operation association information.
	Updates []GetResourceTypesTypeHandlersUpdate `pulumi:"updates"`
}

// GetResourceTypesTypeHandlersInput is an input type that accepts GetResourceTypesTypeHandlersArgs and GetResourceTypesTypeHandlersOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersInput` via:
//
//	GetResourceTypesTypeHandlersArgs{...}
type GetResourceTypesTypeHandlersInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersOutput() GetResourceTypesTypeHandlersOutput
	ToGetResourceTypesTypeHandlersOutputWithContext(context.Context) GetResourceTypesTypeHandlersOutput
}

type GetResourceTypesTypeHandlersArgs struct {
	// Create operation association information.
	Creates GetResourceTypesTypeHandlersCreateArrayInput `pulumi:"creates"`
	// Delete operation association information.
	Deletes GetResourceTypesTypeHandlersDeleteArrayInput `pulumi:"deletes"`
	// Query operation association information.
	Gets GetResourceTypesTypeHandlersGetArrayInput `pulumi:"gets"`
	// List operation association information.
	Lists GetResourceTypesTypeHandlersListArrayInput `pulumi:"lists"`
	// Update operation association information.
	Updates GetResourceTypesTypeHandlersUpdateArrayInput `pulumi:"updates"`
}

func (GetResourceTypesTypeHandlersArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlers)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersArgs) ToGetResourceTypesTypeHandlersOutput() GetResourceTypesTypeHandlersOutput {
	return i.ToGetResourceTypesTypeHandlersOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersArgs) ToGetResourceTypesTypeHandlersOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersOutput)
}

type GetResourceTypesTypeHandlersOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlers)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersOutput) ToGetResourceTypesTypeHandlersOutput() GetResourceTypesTypeHandlersOutput {
	return o
}

func (o GetResourceTypesTypeHandlersOutput) ToGetResourceTypesTypeHandlersOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersOutput {
	return o
}

// Create operation association information.
func (o GetResourceTypesTypeHandlersOutput) Creates() GetResourceTypesTypeHandlersCreateArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlers) []GetResourceTypesTypeHandlersCreate { return v.Creates }).(GetResourceTypesTypeHandlersCreateArrayOutput)
}

// Delete operation association information.
func (o GetResourceTypesTypeHandlersOutput) Deletes() GetResourceTypesTypeHandlersDeleteArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlers) []GetResourceTypesTypeHandlersDelete { return v.Deletes }).(GetResourceTypesTypeHandlersDeleteArrayOutput)
}

// Query operation association information.
func (o GetResourceTypesTypeHandlersOutput) Gets() GetResourceTypesTypeHandlersGetArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlers) []GetResourceTypesTypeHandlersGet { return v.Gets }).(GetResourceTypesTypeHandlersGetArrayOutput)
}

// List operation association information.
func (o GetResourceTypesTypeHandlersOutput) Lists() GetResourceTypesTypeHandlersListArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlers) []GetResourceTypesTypeHandlersList { return v.Lists }).(GetResourceTypesTypeHandlersListArrayOutput)
}

// Update operation association information.
func (o GetResourceTypesTypeHandlersOutput) Updates() GetResourceTypesTypeHandlersUpdateArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlers) []GetResourceTypesTypeHandlersUpdate { return v.Updates }).(GetResourceTypesTypeHandlersUpdateArrayOutput)
}

type GetResourceTypesTypeHandlersCreate struct {
	// The collection of required RAM permission information.
	Permissions []string `pulumi:"permissions"`
}

// GetResourceTypesTypeHandlersCreateInput is an input type that accepts GetResourceTypesTypeHandlersCreateArgs and GetResourceTypesTypeHandlersCreateOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersCreateInput` via:
//
//	GetResourceTypesTypeHandlersCreateArgs{...}
type GetResourceTypesTypeHandlersCreateInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersCreateOutput() GetResourceTypesTypeHandlersCreateOutput
	ToGetResourceTypesTypeHandlersCreateOutputWithContext(context.Context) GetResourceTypesTypeHandlersCreateOutput
}

type GetResourceTypesTypeHandlersCreateArgs struct {
	// The collection of required RAM permission information.
	Permissions pulumi.StringArrayInput `pulumi:"permissions"`
}

func (GetResourceTypesTypeHandlersCreateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersCreate)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersCreateArgs) ToGetResourceTypesTypeHandlersCreateOutput() GetResourceTypesTypeHandlersCreateOutput {
	return i.ToGetResourceTypesTypeHandlersCreateOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersCreateArgs) ToGetResourceTypesTypeHandlersCreateOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersCreateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersCreateOutput)
}

// GetResourceTypesTypeHandlersCreateArrayInput is an input type that accepts GetResourceTypesTypeHandlersCreateArray and GetResourceTypesTypeHandlersCreateArrayOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersCreateArrayInput` via:
//
//	GetResourceTypesTypeHandlersCreateArray{ GetResourceTypesTypeHandlersCreateArgs{...} }
type GetResourceTypesTypeHandlersCreateArrayInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersCreateArrayOutput() GetResourceTypesTypeHandlersCreateArrayOutput
	ToGetResourceTypesTypeHandlersCreateArrayOutputWithContext(context.Context) GetResourceTypesTypeHandlersCreateArrayOutput
}

type GetResourceTypesTypeHandlersCreateArray []GetResourceTypesTypeHandlersCreateInput

func (GetResourceTypesTypeHandlersCreateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersCreate)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersCreateArray) ToGetResourceTypesTypeHandlersCreateArrayOutput() GetResourceTypesTypeHandlersCreateArrayOutput {
	return i.ToGetResourceTypesTypeHandlersCreateArrayOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersCreateArray) ToGetResourceTypesTypeHandlersCreateArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersCreateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersCreateArrayOutput)
}

type GetResourceTypesTypeHandlersCreateOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersCreateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersCreate)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersCreateOutput) ToGetResourceTypesTypeHandlersCreateOutput() GetResourceTypesTypeHandlersCreateOutput {
	return o
}

func (o GetResourceTypesTypeHandlersCreateOutput) ToGetResourceTypesTypeHandlersCreateOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersCreateOutput {
	return o
}

// The collection of required RAM permission information.
func (o GetResourceTypesTypeHandlersCreateOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlersCreate) []string { return v.Permissions }).(pulumi.StringArrayOutput)
}

type GetResourceTypesTypeHandlersCreateArrayOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersCreateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersCreate)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersCreateArrayOutput) ToGetResourceTypesTypeHandlersCreateArrayOutput() GetResourceTypesTypeHandlersCreateArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersCreateArrayOutput) ToGetResourceTypesTypeHandlersCreateArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersCreateArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersCreateArrayOutput) Index(i pulumi.IntInput) GetResourceTypesTypeHandlersCreateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetResourceTypesTypeHandlersCreate {
		return vs[0].([]GetResourceTypesTypeHandlersCreate)[vs[1].(int)]
	}).(GetResourceTypesTypeHandlersCreateOutput)
}

type GetResourceTypesTypeHandlersDelete struct {
	// The collection of required RAM permission information.
	Permissions []string `pulumi:"permissions"`
}

// GetResourceTypesTypeHandlersDeleteInput is an input type that accepts GetResourceTypesTypeHandlersDeleteArgs and GetResourceTypesTypeHandlersDeleteOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersDeleteInput` via:
//
//	GetResourceTypesTypeHandlersDeleteArgs{...}
type GetResourceTypesTypeHandlersDeleteInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersDeleteOutput() GetResourceTypesTypeHandlersDeleteOutput
	ToGetResourceTypesTypeHandlersDeleteOutputWithContext(context.Context) GetResourceTypesTypeHandlersDeleteOutput
}

type GetResourceTypesTypeHandlersDeleteArgs struct {
	// The collection of required RAM permission information.
	Permissions pulumi.StringArrayInput `pulumi:"permissions"`
}

func (GetResourceTypesTypeHandlersDeleteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersDelete)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersDeleteArgs) ToGetResourceTypesTypeHandlersDeleteOutput() GetResourceTypesTypeHandlersDeleteOutput {
	return i.ToGetResourceTypesTypeHandlersDeleteOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersDeleteArgs) ToGetResourceTypesTypeHandlersDeleteOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersDeleteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersDeleteOutput)
}

// GetResourceTypesTypeHandlersDeleteArrayInput is an input type that accepts GetResourceTypesTypeHandlersDeleteArray and GetResourceTypesTypeHandlersDeleteArrayOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersDeleteArrayInput` via:
//
//	GetResourceTypesTypeHandlersDeleteArray{ GetResourceTypesTypeHandlersDeleteArgs{...} }
type GetResourceTypesTypeHandlersDeleteArrayInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersDeleteArrayOutput() GetResourceTypesTypeHandlersDeleteArrayOutput
	ToGetResourceTypesTypeHandlersDeleteArrayOutputWithContext(context.Context) GetResourceTypesTypeHandlersDeleteArrayOutput
}

type GetResourceTypesTypeHandlersDeleteArray []GetResourceTypesTypeHandlersDeleteInput

func (GetResourceTypesTypeHandlersDeleteArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersDelete)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersDeleteArray) ToGetResourceTypesTypeHandlersDeleteArrayOutput() GetResourceTypesTypeHandlersDeleteArrayOutput {
	return i.ToGetResourceTypesTypeHandlersDeleteArrayOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersDeleteArray) ToGetResourceTypesTypeHandlersDeleteArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersDeleteArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersDeleteArrayOutput)
}

type GetResourceTypesTypeHandlersDeleteOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersDeleteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersDelete)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersDeleteOutput) ToGetResourceTypesTypeHandlersDeleteOutput() GetResourceTypesTypeHandlersDeleteOutput {
	return o
}

func (o GetResourceTypesTypeHandlersDeleteOutput) ToGetResourceTypesTypeHandlersDeleteOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersDeleteOutput {
	return o
}

// The collection of required RAM permission information.
func (o GetResourceTypesTypeHandlersDeleteOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlersDelete) []string { return v.Permissions }).(pulumi.StringArrayOutput)
}

type GetResourceTypesTypeHandlersDeleteArrayOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersDeleteArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersDelete)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersDeleteArrayOutput) ToGetResourceTypesTypeHandlersDeleteArrayOutput() GetResourceTypesTypeHandlersDeleteArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersDeleteArrayOutput) ToGetResourceTypesTypeHandlersDeleteArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersDeleteArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersDeleteArrayOutput) Index(i pulumi.IntInput) GetResourceTypesTypeHandlersDeleteOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetResourceTypesTypeHandlersDelete {
		return vs[0].([]GetResourceTypesTypeHandlersDelete)[vs[1].(int)]
	}).(GetResourceTypesTypeHandlersDeleteOutput)
}

type GetResourceTypesTypeHandlersGet struct {
	// The collection of required RAM permission information.
	Permissions []string `pulumi:"permissions"`
}

// GetResourceTypesTypeHandlersGetInput is an input type that accepts GetResourceTypesTypeHandlersGetArgs and GetResourceTypesTypeHandlersGetOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersGetInput` via:
//
//	GetResourceTypesTypeHandlersGetArgs{...}
type GetResourceTypesTypeHandlersGetInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersGetOutput() GetResourceTypesTypeHandlersGetOutput
	ToGetResourceTypesTypeHandlersGetOutputWithContext(context.Context) GetResourceTypesTypeHandlersGetOutput
}

type GetResourceTypesTypeHandlersGetArgs struct {
	// The collection of required RAM permission information.
	Permissions pulumi.StringArrayInput `pulumi:"permissions"`
}

func (GetResourceTypesTypeHandlersGetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersGet)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersGetArgs) ToGetResourceTypesTypeHandlersGetOutput() GetResourceTypesTypeHandlersGetOutput {
	return i.ToGetResourceTypesTypeHandlersGetOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersGetArgs) ToGetResourceTypesTypeHandlersGetOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersGetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersGetOutput)
}

// GetResourceTypesTypeHandlersGetArrayInput is an input type that accepts GetResourceTypesTypeHandlersGetArray and GetResourceTypesTypeHandlersGetArrayOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersGetArrayInput` via:
//
//	GetResourceTypesTypeHandlersGetArray{ GetResourceTypesTypeHandlersGetArgs{...} }
type GetResourceTypesTypeHandlersGetArrayInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersGetArrayOutput() GetResourceTypesTypeHandlersGetArrayOutput
	ToGetResourceTypesTypeHandlersGetArrayOutputWithContext(context.Context) GetResourceTypesTypeHandlersGetArrayOutput
}

type GetResourceTypesTypeHandlersGetArray []GetResourceTypesTypeHandlersGetInput

func (GetResourceTypesTypeHandlersGetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersGet)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersGetArray) ToGetResourceTypesTypeHandlersGetArrayOutput() GetResourceTypesTypeHandlersGetArrayOutput {
	return i.ToGetResourceTypesTypeHandlersGetArrayOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersGetArray) ToGetResourceTypesTypeHandlersGetArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersGetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersGetArrayOutput)
}

type GetResourceTypesTypeHandlersGetOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersGetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersGet)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersGetOutput) ToGetResourceTypesTypeHandlersGetOutput() GetResourceTypesTypeHandlersGetOutput {
	return o
}

func (o GetResourceTypesTypeHandlersGetOutput) ToGetResourceTypesTypeHandlersGetOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersGetOutput {
	return o
}

// The collection of required RAM permission information.
func (o GetResourceTypesTypeHandlersGetOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlersGet) []string { return v.Permissions }).(pulumi.StringArrayOutput)
}

type GetResourceTypesTypeHandlersGetArrayOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersGetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersGet)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersGetArrayOutput) ToGetResourceTypesTypeHandlersGetArrayOutput() GetResourceTypesTypeHandlersGetArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersGetArrayOutput) ToGetResourceTypesTypeHandlersGetArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersGetArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersGetArrayOutput) Index(i pulumi.IntInput) GetResourceTypesTypeHandlersGetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetResourceTypesTypeHandlersGet {
		return vs[0].([]GetResourceTypesTypeHandlersGet)[vs[1].(int)]
	}).(GetResourceTypesTypeHandlersGetOutput)
}

type GetResourceTypesTypeHandlersList struct {
	// The collection of required RAM permission information.
	Permissions []string `pulumi:"permissions"`
}

// GetResourceTypesTypeHandlersListInput is an input type that accepts GetResourceTypesTypeHandlersListArgs and GetResourceTypesTypeHandlersListOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersListInput` via:
//
//	GetResourceTypesTypeHandlersListArgs{...}
type GetResourceTypesTypeHandlersListInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersListOutput() GetResourceTypesTypeHandlersListOutput
	ToGetResourceTypesTypeHandlersListOutputWithContext(context.Context) GetResourceTypesTypeHandlersListOutput
}

type GetResourceTypesTypeHandlersListArgs struct {
	// The collection of required RAM permission information.
	Permissions pulumi.StringArrayInput `pulumi:"permissions"`
}

func (GetResourceTypesTypeHandlersListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersList)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersListArgs) ToGetResourceTypesTypeHandlersListOutput() GetResourceTypesTypeHandlersListOutput {
	return i.ToGetResourceTypesTypeHandlersListOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersListArgs) ToGetResourceTypesTypeHandlersListOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersListOutput)
}

// GetResourceTypesTypeHandlersListArrayInput is an input type that accepts GetResourceTypesTypeHandlersListArray and GetResourceTypesTypeHandlersListArrayOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersListArrayInput` via:
//
//	GetResourceTypesTypeHandlersListArray{ GetResourceTypesTypeHandlersListArgs{...} }
type GetResourceTypesTypeHandlersListArrayInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersListArrayOutput() GetResourceTypesTypeHandlersListArrayOutput
	ToGetResourceTypesTypeHandlersListArrayOutputWithContext(context.Context) GetResourceTypesTypeHandlersListArrayOutput
}

type GetResourceTypesTypeHandlersListArray []GetResourceTypesTypeHandlersListInput

func (GetResourceTypesTypeHandlersListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersList)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersListArray) ToGetResourceTypesTypeHandlersListArrayOutput() GetResourceTypesTypeHandlersListArrayOutput {
	return i.ToGetResourceTypesTypeHandlersListArrayOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersListArray) ToGetResourceTypesTypeHandlersListArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersListArrayOutput)
}

type GetResourceTypesTypeHandlersListOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersList)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersListOutput) ToGetResourceTypesTypeHandlersListOutput() GetResourceTypesTypeHandlersListOutput {
	return o
}

func (o GetResourceTypesTypeHandlersListOutput) ToGetResourceTypesTypeHandlersListOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersListOutput {
	return o
}

// The collection of required RAM permission information.
func (o GetResourceTypesTypeHandlersListOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlersList) []string { return v.Permissions }).(pulumi.StringArrayOutput)
}

type GetResourceTypesTypeHandlersListArrayOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersList)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersListArrayOutput) ToGetResourceTypesTypeHandlersListArrayOutput() GetResourceTypesTypeHandlersListArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersListArrayOutput) ToGetResourceTypesTypeHandlersListArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersListArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersListArrayOutput) Index(i pulumi.IntInput) GetResourceTypesTypeHandlersListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetResourceTypesTypeHandlersList {
		return vs[0].([]GetResourceTypesTypeHandlersList)[vs[1].(int)]
	}).(GetResourceTypesTypeHandlersListOutput)
}

type GetResourceTypesTypeHandlersUpdate struct {
	// The collection of required RAM permission information.
	Permissions []string `pulumi:"permissions"`
}

// GetResourceTypesTypeHandlersUpdateInput is an input type that accepts GetResourceTypesTypeHandlersUpdateArgs and GetResourceTypesTypeHandlersUpdateOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersUpdateInput` via:
//
//	GetResourceTypesTypeHandlersUpdateArgs{...}
type GetResourceTypesTypeHandlersUpdateInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersUpdateOutput() GetResourceTypesTypeHandlersUpdateOutput
	ToGetResourceTypesTypeHandlersUpdateOutputWithContext(context.Context) GetResourceTypesTypeHandlersUpdateOutput
}

type GetResourceTypesTypeHandlersUpdateArgs struct {
	// The collection of required RAM permission information.
	Permissions pulumi.StringArrayInput `pulumi:"permissions"`
}

func (GetResourceTypesTypeHandlersUpdateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersUpdate)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersUpdateArgs) ToGetResourceTypesTypeHandlersUpdateOutput() GetResourceTypesTypeHandlersUpdateOutput {
	return i.ToGetResourceTypesTypeHandlersUpdateOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersUpdateArgs) ToGetResourceTypesTypeHandlersUpdateOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersUpdateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersUpdateOutput)
}

// GetResourceTypesTypeHandlersUpdateArrayInput is an input type that accepts GetResourceTypesTypeHandlersUpdateArray and GetResourceTypesTypeHandlersUpdateArrayOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeHandlersUpdateArrayInput` via:
//
//	GetResourceTypesTypeHandlersUpdateArray{ GetResourceTypesTypeHandlersUpdateArgs{...} }
type GetResourceTypesTypeHandlersUpdateArrayInput interface {
	pulumi.Input

	ToGetResourceTypesTypeHandlersUpdateArrayOutput() GetResourceTypesTypeHandlersUpdateArrayOutput
	ToGetResourceTypesTypeHandlersUpdateArrayOutputWithContext(context.Context) GetResourceTypesTypeHandlersUpdateArrayOutput
}

type GetResourceTypesTypeHandlersUpdateArray []GetResourceTypesTypeHandlersUpdateInput

func (GetResourceTypesTypeHandlersUpdateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersUpdate)(nil)).Elem()
}

func (i GetResourceTypesTypeHandlersUpdateArray) ToGetResourceTypesTypeHandlersUpdateArrayOutput() GetResourceTypesTypeHandlersUpdateArrayOutput {
	return i.ToGetResourceTypesTypeHandlersUpdateArrayOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeHandlersUpdateArray) ToGetResourceTypesTypeHandlersUpdateArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersUpdateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeHandlersUpdateArrayOutput)
}

type GetResourceTypesTypeHandlersUpdateOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersUpdateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeHandlersUpdate)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersUpdateOutput) ToGetResourceTypesTypeHandlersUpdateOutput() GetResourceTypesTypeHandlersUpdateOutput {
	return o
}

func (o GetResourceTypesTypeHandlersUpdateOutput) ToGetResourceTypesTypeHandlersUpdateOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersUpdateOutput {
	return o
}

// The collection of required RAM permission information.
func (o GetResourceTypesTypeHandlersUpdateOutput) Permissions() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetResourceTypesTypeHandlersUpdate) []string { return v.Permissions }).(pulumi.StringArrayOutput)
}

type GetResourceTypesTypeHandlersUpdateArrayOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeHandlersUpdateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeHandlersUpdate)(nil)).Elem()
}

func (o GetResourceTypesTypeHandlersUpdateArrayOutput) ToGetResourceTypesTypeHandlersUpdateArrayOutput() GetResourceTypesTypeHandlersUpdateArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersUpdateArrayOutput) ToGetResourceTypesTypeHandlersUpdateArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeHandlersUpdateArrayOutput {
	return o
}

func (o GetResourceTypesTypeHandlersUpdateArrayOutput) Index(i pulumi.IntInput) GetResourceTypesTypeHandlersUpdateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetResourceTypesTypeHandlersUpdate {
		return vs[0].([]GetResourceTypesTypeHandlersUpdate)[vs[1].(int)]
	}).(GetResourceTypesTypeHandlersUpdateOutput)
}

type GetResourceTypesTypeInfo struct {
	// Payment formpaid (paid)(free).
	ChargeType string `pulumi:"chargeType"`
	// Delivery Levelcenter (centralized deployment level)region (regional deployment level)zone (Availability zone deployment level).
	DeliveryScope string `pulumi:"deliveryScope"`
	// Resource type description.
	Description string `pulumi:"description"`
	// The resource type name.
	Title string `pulumi:"title"`
}

// GetResourceTypesTypeInfoInput is an input type that accepts GetResourceTypesTypeInfoArgs and GetResourceTypesTypeInfoOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeInfoInput` via:
//
//	GetResourceTypesTypeInfoArgs{...}
type GetResourceTypesTypeInfoInput interface {
	pulumi.Input

	ToGetResourceTypesTypeInfoOutput() GetResourceTypesTypeInfoOutput
	ToGetResourceTypesTypeInfoOutputWithContext(context.Context) GetResourceTypesTypeInfoOutput
}

type GetResourceTypesTypeInfoArgs struct {
	// Payment formpaid (paid)(free).
	ChargeType pulumi.StringInput `pulumi:"chargeType"`
	// Delivery Levelcenter (centralized deployment level)region (regional deployment level)zone (Availability zone deployment level).
	DeliveryScope pulumi.StringInput `pulumi:"deliveryScope"`
	// Resource type description.
	Description pulumi.StringInput `pulumi:"description"`
	// The resource type name.
	Title pulumi.StringInput `pulumi:"title"`
}

func (GetResourceTypesTypeInfoArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeInfo)(nil)).Elem()
}

func (i GetResourceTypesTypeInfoArgs) ToGetResourceTypesTypeInfoOutput() GetResourceTypesTypeInfoOutput {
	return i.ToGetResourceTypesTypeInfoOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeInfoArgs) ToGetResourceTypesTypeInfoOutputWithContext(ctx context.Context) GetResourceTypesTypeInfoOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeInfoOutput)
}

// GetResourceTypesTypeInfoArrayInput is an input type that accepts GetResourceTypesTypeInfoArray and GetResourceTypesTypeInfoArrayOutput values.
// You can construct a concrete instance of `GetResourceTypesTypeInfoArrayInput` via:
//
//	GetResourceTypesTypeInfoArray{ GetResourceTypesTypeInfoArgs{...} }
type GetResourceTypesTypeInfoArrayInput interface {
	pulumi.Input

	ToGetResourceTypesTypeInfoArrayOutput() GetResourceTypesTypeInfoArrayOutput
	ToGetResourceTypesTypeInfoArrayOutputWithContext(context.Context) GetResourceTypesTypeInfoArrayOutput
}

type GetResourceTypesTypeInfoArray []GetResourceTypesTypeInfoInput

func (GetResourceTypesTypeInfoArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeInfo)(nil)).Elem()
}

func (i GetResourceTypesTypeInfoArray) ToGetResourceTypesTypeInfoArrayOutput() GetResourceTypesTypeInfoArrayOutput {
	return i.ToGetResourceTypesTypeInfoArrayOutputWithContext(context.Background())
}

func (i GetResourceTypesTypeInfoArray) ToGetResourceTypesTypeInfoArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeInfoArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetResourceTypesTypeInfoArrayOutput)
}

type GetResourceTypesTypeInfoOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeInfoOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetResourceTypesTypeInfo)(nil)).Elem()
}

func (o GetResourceTypesTypeInfoOutput) ToGetResourceTypesTypeInfoOutput() GetResourceTypesTypeInfoOutput {
	return o
}

func (o GetResourceTypesTypeInfoOutput) ToGetResourceTypesTypeInfoOutputWithContext(ctx context.Context) GetResourceTypesTypeInfoOutput {
	return o
}

// Payment formpaid (paid)(free).
func (o GetResourceTypesTypeInfoOutput) ChargeType() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesTypeInfo) string { return v.ChargeType }).(pulumi.StringOutput)
}

// Delivery Levelcenter (centralized deployment level)region (regional deployment level)zone (Availability zone deployment level).
func (o GetResourceTypesTypeInfoOutput) DeliveryScope() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesTypeInfo) string { return v.DeliveryScope }).(pulumi.StringOutput)
}

// Resource type description.
func (o GetResourceTypesTypeInfoOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesTypeInfo) string { return v.Description }).(pulumi.StringOutput)
}

// The resource type name.
func (o GetResourceTypesTypeInfoOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v GetResourceTypesTypeInfo) string { return v.Title }).(pulumi.StringOutput)
}

type GetResourceTypesTypeInfoArrayOutput struct{ *pulumi.OutputState }

func (GetResourceTypesTypeInfoArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetResourceTypesTypeInfo)(nil)).Elem()
}

func (o GetResourceTypesTypeInfoArrayOutput) ToGetResourceTypesTypeInfoArrayOutput() GetResourceTypesTypeInfoArrayOutput {
	return o
}

func (o GetResourceTypesTypeInfoArrayOutput) ToGetResourceTypesTypeInfoArrayOutputWithContext(ctx context.Context) GetResourceTypesTypeInfoArrayOutput {
	return o
}

func (o GetResourceTypesTypeInfoArrayOutput) Index(i pulumi.IntInput) GetResourceTypesTypeInfoOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetResourceTypesTypeInfo {
		return vs[0].([]GetResourceTypesTypeInfo)[vs[1].(int)]
	}).(GetResourceTypesTypeInfoOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GetPricesPriceInput)(nil)).Elem(), GetPricesPriceArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPricesPriceArrayInput)(nil)).Elem(), GetPricesPriceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPricesPriceModuleDetailInput)(nil)).Elem(), GetPricesPriceModuleDetailArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPricesPriceModuleDetailArrayInput)(nil)).Elem(), GetPricesPriceModuleDetailArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPricesPricePromotionDetailInput)(nil)).Elem(), GetPricesPricePromotionDetailArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetPricesPricePromotionDetailArrayInput)(nil)).Elem(), GetPricesPricePromotionDetailArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetProductsProductInput)(nil)).Elem(), GetProductsProductArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetProductsProductArrayInput)(nil)).Elem(), GetProductsProductArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeInput)(nil)).Elem(), GetResourceTypesTypeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeArrayInput)(nil)).Elem(), GetResourceTypesTypeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersInput)(nil)).Elem(), GetResourceTypesTypeHandlersArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersCreateInput)(nil)).Elem(), GetResourceTypesTypeHandlersCreateArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersCreateArrayInput)(nil)).Elem(), GetResourceTypesTypeHandlersCreateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersDeleteInput)(nil)).Elem(), GetResourceTypesTypeHandlersDeleteArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersDeleteArrayInput)(nil)).Elem(), GetResourceTypesTypeHandlersDeleteArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersGetInput)(nil)).Elem(), GetResourceTypesTypeHandlersGetArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersGetArrayInput)(nil)).Elem(), GetResourceTypesTypeHandlersGetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersListInput)(nil)).Elem(), GetResourceTypesTypeHandlersListArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersListArrayInput)(nil)).Elem(), GetResourceTypesTypeHandlersListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersUpdateInput)(nil)).Elem(), GetResourceTypesTypeHandlersUpdateArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeHandlersUpdateArrayInput)(nil)).Elem(), GetResourceTypesTypeHandlersUpdateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeInfoInput)(nil)).Elem(), GetResourceTypesTypeInfoArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetResourceTypesTypeInfoArrayInput)(nil)).Elem(), GetResourceTypesTypeInfoArray{})
	pulumi.RegisterOutputType(GetPricesPriceOutput{})
	pulumi.RegisterOutputType(GetPricesPriceArrayOutput{})
	pulumi.RegisterOutputType(GetPricesPriceModuleDetailOutput{})
	pulumi.RegisterOutputType(GetPricesPriceModuleDetailArrayOutput{})
	pulumi.RegisterOutputType(GetPricesPricePromotionDetailOutput{})
	pulumi.RegisterOutputType(GetPricesPricePromotionDetailArrayOutput{})
	pulumi.RegisterOutputType(GetProductsProductOutput{})
	pulumi.RegisterOutputType(GetProductsProductArrayOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeArrayOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersCreateOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersCreateArrayOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersDeleteOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersDeleteArrayOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersGetOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersGetArrayOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersListOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersListArrayOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersUpdateOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeHandlersUpdateArrayOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeInfoOutput{})
	pulumi.RegisterOutputType(GetResourceTypesTypeInfoArrayOutput{})
}
