// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.ehpc.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClusterV2ManagerScheduler {
    /**
     * @return The scheduler type. Valid values:
     * 
     * - SLURM
     * - PBS
     * - OPENGRIDSCHEDULER
     * - LSF_PLUGIN
     * - PBS_PLUGIN
     * 
     */
    private @Nullable String type;
    private @Nullable String version;

    private ClusterV2ManagerScheduler() {}
    /**
     * @return The scheduler type. Valid values:
     * 
     * - SLURM
     * - PBS
     * - OPENGRIDSCHEDULER
     * - LSF_PLUGIN
     * - PBS_PLUGIN
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClusterV2ManagerScheduler defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String type;
        private @Nullable String version;
        public Builder() {}
        public Builder(ClusterV2ManagerScheduler defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.type = defaults.type;
    	      this.version = defaults.version;
        }

        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        @CustomType.Setter
        public Builder version(@Nullable String version) {

            this.version = version;
            return this;
        }
        public ClusterV2ManagerScheduler build() {
            final var _resultValue = new ClusterV2ManagerScheduler();
            _resultValue.type = type;
            _resultValue.version = version;
            return _resultValue;
        }
    }
}
