// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.ApiGateway.Outputs
{

    [OutputType]
    public sealed class ApiSystemParameter
    {
        /// <summary>
        /// Request's parameter location; values: BODY, HEAD, QUERY, and PATH.
        /// </summary>
        public readonly string In;
        /// <summary>
        /// The name of the api gateway api. Defaults to null.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Backend service's parameter name.
        /// </summary>
        public readonly string NameService;

        [OutputConstructor]
        private ApiSystemParameter(
            string @in,

            string name,

            string nameService)
        {
            In = @in;
            Name = name;
            NameService = nameService;
        }
    }
}
