// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.ActionTrail
{
    public static class GetHistoryDeliveryJobs
    {
        /// <summary>
        /// This data source provides the Actiontrail History Delivery Jobs of the current Alibaba Cloud user.
        /// 
        /// &gt; **NOTE:** Available in v1.139.0+.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// Basic Usage
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using AliCloud = Pulumi.AliCloud;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var ids = Output.Create(AliCloud.ActionTrail.GetHistoryDeliveryJobs.InvokeAsync(new AliCloud.ActionTrail.GetHistoryDeliveryJobsArgs
        ///         {
        ///             Ids = 
        ///             {
        ///                 "example_id",
        ///             },
        ///         }));
        ///         this.ActiontrailHistoryDeliveryJobId1 = ids.Apply(ids =&gt; ids.Jobs[0].Id);
        ///         var status = Output.Create(AliCloud.ActionTrail.GetHistoryDeliveryJobs.InvokeAsync(new AliCloud.ActionTrail.GetHistoryDeliveryJobsArgs
        ///         {
        ///             Ids = 
        ///             {
        ///                 "example_id",
        ///             },
        ///             Status = 2,
        ///         }));
        ///         this.ActiontrailHistoryDeliveryJobId2 = status.Apply(status =&gt; status.Jobs[0].Id);
        ///     }
        /// 
        ///     [Output("actiontrailHistoryDeliveryJobId1")]
        ///     public Output&lt;string&gt; ActiontrailHistoryDeliveryJobId1 { get; set; }
        ///     [Output("actiontrailHistoryDeliveryJobId2")]
        ///     public Output&lt;string&gt; ActiontrailHistoryDeliveryJobId2 { get; set; }
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetHistoryDeliveryJobsResult> InvokeAsync(GetHistoryDeliveryJobsArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetHistoryDeliveryJobsResult>("alicloud:actiontrail/getHistoryDeliveryJobs:getHistoryDeliveryJobs", args ?? new GetHistoryDeliveryJobsArgs(), options.WithVersion());
    }


    public sealed class GetHistoryDeliveryJobsArgs : Pulumi.InvokeArgs
    {
        [Input("enableDetails")]
        public bool? EnableDetails { get; set; }

        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// A list of History Delivery Job IDs.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        [Input("outputFile")]
        public string? OutputFile { get; set; }

        /// <summary>
        /// The status of the task. Valid values: `0`, `1`, `2`, `3`. `0`: The task is initializing. `1`: The task is delivering historical events. `2`: The delivery of historical events is complete. `3`: The task fails.
        /// </summary>
        [Input("status")]
        public int? Status { get; set; }

        public GetHistoryDeliveryJobsArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetHistoryDeliveryJobsResult
    {
        public readonly bool? EnableDetails;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        public readonly ImmutableArray<Outputs.GetHistoryDeliveryJobsJobResult> Jobs;
        public readonly string? OutputFile;
        public readonly int? Status;

        [OutputConstructor]
        private GetHistoryDeliveryJobsResult(
            bool? enableDetails,

            string id,

            ImmutableArray<string> ids,

            ImmutableArray<Outputs.GetHistoryDeliveryJobsJobResult> jobs,

            string? outputFile,

            int? status)
        {
            EnableDetails = enableDetails;
            Id = id;
            Ids = ids;
            Jobs = jobs;
            OutputFile = outputFile;
            Status = status;
        }
    }
}
