// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * This data source provides the Gpdb Accounts of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available in v1.142.0+.
 *
 * ## Example Usage
 *
 * Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as alicloud from "@pulumi/alicloud";
 *
 * const ids = alicloud.gpdb.getAccounts({
 *     dbInstanceId: "example_value",
 *     ids: [
 *         "my-Account-1",
 *         "my-Account-2",
 *     ],
 * });
 * export const gpdbAccountId1 = ids.then(ids => ids.accounts?[0]?.id);
 * const nameRegex = alicloud.gpdb.getAccounts({
 *     dbInstanceId: "example_value",
 *     nameRegex: "^my-Account",
 * });
 * export const gpdbAccountId2 = nameRegex.then(nameRegex => nameRegex.accounts?[0]?.id);
 * ```
 */
export function getAccounts(args: GetAccountsArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("alicloud:gpdb/getAccounts:getAccounts", {
        "dbInstanceId": args.dbInstanceId,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccounts.
 */
export interface GetAccountsArgs {
    /**
     * The ID of the instance.
     */
    dbInstanceId: string;
    /**
     * A list of Account IDs. Its element value is same as Account Name.
     */
    ids?: string[];
    /**
     * A regex string to filter results by Account name.
     */
    nameRegex?: string;
    outputFile?: string;
    /**
     * The status of the account. Valid values: `Active`, `Creating` and `Deleting`.
     */
    status?: string;
}

/**
 * A collection of values returned by getAccounts.
 */
export interface GetAccountsResult {
    readonly accounts: outputs.gpdb.GetAccountsAccount[];
    readonly dbInstanceId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    readonly nameRegex?: string;
    readonly names: string[];
    readonly outputFile?: string;
    readonly status?: string;
}

export function getAccountsOutput(args: GetAccountsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAccountsResult> {
    return pulumi.output(args).apply(a => getAccounts(a, opts))
}

/**
 * A collection of arguments for invoking getAccounts.
 */
export interface GetAccountsOutputArgs {
    /**
     * The ID of the instance.
     */
    dbInstanceId: pulumi.Input<string>;
    /**
     * A list of Account IDs. Its element value is same as Account Name.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A regex string to filter results by Account name.
     */
    nameRegex?: pulumi.Input<string>;
    outputFile?: pulumi.Input<string>;
    /**
     * The status of the account. Valid values: `Active`, `Creating` and `Deleting`.
     */
    status?: pulumi.Input<string>;
}
