provider: alicloud
major-version: 3
lint: false
parallel: 1
env:
  ALICLOUD_ACCESS_KEY: ${{ secrets.ALICLOUD_ACCESS_KEY }}
  ALICLOUD_REGION: "us-west-1"
  ALICLOUD_SECRET_KEY: ${{ secrets.ALICLOUD_SECRET_KEY }}
# The maintainers of the TF provider keep misspelled resources around in order
# to avoid breaking changes. We do not want to map these. This means that
# maintainers of the Pulumi repo must manually check the output for missing
# mappings until we are able to explicitly able to tell tfgen that a mapping is
# intentionally ignored.
fail-on-missing-mapping: false
makeTemplate: bridged
plugins:
  - name: random 
    version: "4.3.1"
javaGenVersion: "v0.9.8"
team: ecosystem
license:
  ignore:
    # These projects don't have a LICENSE file, but do say mention (in README.md) that
    # they are under Apache-2.0.
    - github.com/alibabacloud-go/endpoint-util/service
    - github.com/alibabacloud-go/tea-roa-utils/service
    - github.com/alibabacloud-go/tea-roa/client
    - github.com/alibabacloud-go/tea-rpc-utils/service
    - github.com/alibabacloud-go/tea-rpc/client
    - github.com/alibabacloud-go/tea-xml/service
    - github.com/alibabacloud-go/darabonba-string/client

    # These projects are generated wrapper libraries, and do not contain any mention of a
    # license.
    - github.com/alibabacloud-go/alibabacloud-gateway-sls-util/client
    - github.com/alibabacloud-go/alibabacloud-gateway-sls/client
    - github.com/alibabacloud-go/darabonba-array/client
    - github.com/alibabacloud-go/darabonba-encode-util/client
    - github.com/alibabacloud-go/darabonba-map/client
    - github.com/alibabacloud-go/darabonba-signature-util/client
