// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.fc.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class V2FunctionCode {
    /**
     * @return The OSS bucket name of the function code package.
     * 
     */
    private @Nullable String ossBucketName;
    /**
     * @return The OSS object name of the function code package.
     * 
     */
    private @Nullable String ossObjectName;
    /**
     * @return Upload the base64 encoding of the code zip package directly in the request body.
     * 
     */
    private @Nullable String zipFile;

    private V2FunctionCode() {}
    /**
     * @return The OSS bucket name of the function code package.
     * 
     */
    public Optional<String> ossBucketName() {
        return Optional.ofNullable(this.ossBucketName);
    }
    /**
     * @return The OSS object name of the function code package.
     * 
     */
    public Optional<String> ossObjectName() {
        return Optional.ofNullable(this.ossObjectName);
    }
    /**
     * @return Upload the base64 encoding of the code zip package directly in the request body.
     * 
     */
    public Optional<String> zipFile() {
        return Optional.ofNullable(this.zipFile);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(V2FunctionCode defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String ossBucketName;
        private @Nullable String ossObjectName;
        private @Nullable String zipFile;
        public Builder() {}
        public Builder(V2FunctionCode defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ossBucketName = defaults.ossBucketName;
    	      this.ossObjectName = defaults.ossObjectName;
    	      this.zipFile = defaults.zipFile;
        }

        @CustomType.Setter
        public Builder ossBucketName(@Nullable String ossBucketName) {
            this.ossBucketName = ossBucketName;
            return this;
        }
        @CustomType.Setter
        public Builder ossObjectName(@Nullable String ossObjectName) {
            this.ossObjectName = ossObjectName;
            return this;
        }
        @CustomType.Setter
        public Builder zipFile(@Nullable String zipFile) {
            this.zipFile = zipFile;
            return this;
        }
        public V2FunctionCode build() {
            final var _resultValue = new V2FunctionCode();
            _resultValue.ossBucketName = ossBucketName;
            _resultValue.ossObjectName = ossObjectName;
            _resultValue.zipFile = zipFile;
            return _resultValue;
        }
    }
}
