// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.cloudcontrol.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetResourceTypesTypeHandlersList {
    /**
     * @return The collection of required RAM permission information.
     * 
     */
    private List<String> permissions;

    private GetResourceTypesTypeHandlersList() {}
    /**
     * @return The collection of required RAM permission information.
     * 
     */
    public List<String> permissions() {
        return this.permissions;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetResourceTypesTypeHandlersList defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> permissions;
        public Builder() {}
        public Builder(GetResourceTypesTypeHandlersList defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.permissions = defaults.permissions;
        }

        @CustomType.Setter
        public Builder permissions(List<String> permissions) {
            if (permissions == null) {
              throw new MissingRequiredPropertyException("GetResourceTypesTypeHandlersList", "permissions");
            }
            this.permissions = permissions;
            return this;
        }
        public Builder permissions(String... permissions) {
            return permissions(List.of(permissions));
        }
        public GetResourceTypesTypeHandlersList build() {
            final var _resultValue = new GetResourceTypesTypeHandlersList();
            _resultValue.permissions = permissions;
            return _resultValue;
        }
    }
}
