// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.Oss.Outputs
{

    [OutputType]
    public sealed class BucketInventoryDestination
    {
        /// <summary>
        /// The Bucket information stored after the list result is exported. See `OssBucketDestination` below.
        /// </summary>
        public readonly Outputs.BucketInventoryDestinationOssBucketDestination? OssBucketDestination;

        [OutputConstructor]
        private BucketInventoryDestination(Outputs.BucketInventoryDestinationOssBucketDestination? ossBucketDestination)
        {
            OssBucketDestination = ossBucketDestination;
        }
    }
}
