// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.expressconnect.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetRouterTrAssociationsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetRouterTrAssociationsPlainArgs Empty = new GetRouterTrAssociationsPlainArgs();

    /**
     * The ID of the association between the Express Connect Router and the TR.
     * 
     */
    @Import(name="associationId")
    private @Nullable String associationId;

    /**
     * @return The ID of the association between the Express Connect Router and the TR.
     * 
     */
    public Optional<String> associationId() {
        return Optional.ofNullable(this.associationId);
    }

    /**
     * The region ID of the associated TR.
     * 
     */
    @Import(name="associationRegionId")
    private @Nullable String associationRegionId;

    /**
     * @return The region ID of the associated TR.
     * 
     */
    public Optional<String> associationRegionId() {
        return Optional.ofNullable(this.associationRegionId);
    }

    /**
     * The ID of the Cloud Enterprise Network instance.
     * 
     */
    @Import(name="cenId")
    private @Nullable String cenId;

    /**
     * @return The ID of the Cloud Enterprise Network instance.
     * 
     */
    public Optional<String> cenId() {
        return Optional.ofNullable(this.cenId);
    }

    /**
     * The ID of the Express Connect Router instance.
     * 
     */
    @Import(name="ecrId", required=true)
    private String ecrId;

    /**
     * @return The ID of the Express Connect Router instance.
     * 
     */
    public String ecrId() {
        return this.ecrId;
    }

    /**
     * A list of Tr Association IDs.
     * 
     */
    @Import(name="ids")
    private @Nullable List<String> ids;

    /**
     * @return A list of Tr Association IDs.
     * 
     */
    public Optional<List<String>> ids() {
        return Optional.ofNullable(this.ids);
    }

    /**
     * File name where to save data source results (after running `pulumi preview`).
     * 
     */
    @Import(name="outputFile")
    private @Nullable String outputFile;

    /**
     * @return File name where to save data source results (after running `pulumi preview`).
     * 
     */
    public Optional<String> outputFile() {
        return Optional.ofNullable(this.outputFile);
    }

    /**
     * The status of the association. Valid values: `CREATING`, `ACTIVE`, `INACTIVE`, `ASSOCIATING`, `DISSOCIATING`, `UPDATING`, `DELETING`.
     * 
     */
    @Import(name="status")
    private @Nullable String status;

    /**
     * @return The status of the association. Valid values: `CREATING`, `ACTIVE`, `INACTIVE`, `ASSOCIATING`, `DISSOCIATING`, `UPDATING`, `DELETING`.
     * 
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }

    /**
     * The ID of the transit router instance.
     * 
     */
    @Import(name="transitRouterId")
    private @Nullable String transitRouterId;

    /**
     * @return The ID of the transit router instance.
     * 
     */
    public Optional<String> transitRouterId() {
        return Optional.ofNullable(this.transitRouterId);
    }

    private GetRouterTrAssociationsPlainArgs() {}

    private GetRouterTrAssociationsPlainArgs(GetRouterTrAssociationsPlainArgs $) {
        this.associationId = $.associationId;
        this.associationRegionId = $.associationRegionId;
        this.cenId = $.cenId;
        this.ecrId = $.ecrId;
        this.ids = $.ids;
        this.outputFile = $.outputFile;
        this.status = $.status;
        this.transitRouterId = $.transitRouterId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetRouterTrAssociationsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetRouterTrAssociationsPlainArgs $;

        public Builder() {
            $ = new GetRouterTrAssociationsPlainArgs();
        }

        public Builder(GetRouterTrAssociationsPlainArgs defaults) {
            $ = new GetRouterTrAssociationsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param associationId The ID of the association between the Express Connect Router and the TR.
         * 
         * @return builder
         * 
         */
        public Builder associationId(@Nullable String associationId) {
            $.associationId = associationId;
            return this;
        }

        /**
         * @param associationRegionId The region ID of the associated TR.
         * 
         * @return builder
         * 
         */
        public Builder associationRegionId(@Nullable String associationRegionId) {
            $.associationRegionId = associationRegionId;
            return this;
        }

        /**
         * @param cenId The ID of the Cloud Enterprise Network instance.
         * 
         * @return builder
         * 
         */
        public Builder cenId(@Nullable String cenId) {
            $.cenId = cenId;
            return this;
        }

        /**
         * @param ecrId The ID of the Express Connect Router instance.
         * 
         * @return builder
         * 
         */
        public Builder ecrId(String ecrId) {
            $.ecrId = ecrId;
            return this;
        }

        /**
         * @param ids A list of Tr Association IDs.
         * 
         * @return builder
         * 
         */
        public Builder ids(@Nullable List<String> ids) {
            $.ids = ids;
            return this;
        }

        /**
         * @param ids A list of Tr Association IDs.
         * 
         * @return builder
         * 
         */
        public Builder ids(String... ids) {
            return ids(List.of(ids));
        }

        /**
         * @param outputFile File name where to save data source results (after running `pulumi preview`).
         * 
         * @return builder
         * 
         */
        public Builder outputFile(@Nullable String outputFile) {
            $.outputFile = outputFile;
            return this;
        }

        /**
         * @param status The status of the association. Valid values: `CREATING`, `ACTIVE`, `INACTIVE`, `ASSOCIATING`, `DISSOCIATING`, `UPDATING`, `DELETING`.
         * 
         * @return builder
         * 
         */
        public Builder status(@Nullable String status) {
            $.status = status;
            return this;
        }

        /**
         * @param transitRouterId The ID of the transit router instance.
         * 
         * @return builder
         * 
         */
        public Builder transitRouterId(@Nullable String transitRouterId) {
            $.transitRouterId = transitRouterId;
            return this;
        }

        public GetRouterTrAssociationsPlainArgs build() {
            if ($.ecrId == null) {
                throw new MissingRequiredPropertyException("GetRouterTrAssociationsPlainArgs", "ecrId");
            }
            return $;
        }
    }

}
