// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.FC.Inputs
{

    public sealed class V2FunctionCodeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The OSS bucket name of the function code package.
        /// </summary>
        [Input("ossBucketName")]
        public Input<string>? OssBucketName { get; set; }

        /// <summary>
        /// The OSS object name of the function code package.
        /// </summary>
        [Input("ossObjectName")]
        public Input<string>? OssObjectName { get; set; }

        /// <summary>
        /// Upload the base64 encoding of the code zip package directly in the request body.
        /// </summary>
        [Input("zipFile")]
        public Input<string>? ZipFile { get; set; }

        public V2FunctionCodeArgs()
        {
        }
        public static new V2FunctionCodeArgs Empty => new V2FunctionCodeArgs();
    }
}
