// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.cms.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class AlarmCompositeExpressionExpressionList {
    private @Nullable String comparisonOperator;
    /**
     * @return The metric that is used to monitor the cloud service.
     * 
     */
    private @Nullable String metricName;
    /**
     * @return The statistical period of the metric. Unit: seconds. Default value: `300`.
     * 
     */
    private @Nullable String period;
    /**
     * @return Field `statistics` has been removed from provider version 1.216.0. New field `escalations_critical.statistics` instead.
     * 
     */
    private @Nullable String statistics;
    /**
     * @return Field `threshold` has been removed from provider version 1.216.0. New field `escalations_critical.threshold` instead.
     * 
     */
    private @Nullable String threshold;

    private AlarmCompositeExpressionExpressionList() {}
    public Optional<String> comparisonOperator() {
        return Optional.ofNullable(this.comparisonOperator);
    }
    /**
     * @return The metric that is used to monitor the cloud service.
     * 
     */
    public Optional<String> metricName() {
        return Optional.ofNullable(this.metricName);
    }
    /**
     * @return The statistical period of the metric. Unit: seconds. Default value: `300`.
     * 
     */
    public Optional<String> period() {
        return Optional.ofNullable(this.period);
    }
    /**
     * @return Field `statistics` has been removed from provider version 1.216.0. New field `escalations_critical.statistics` instead.
     * 
     */
    public Optional<String> statistics() {
        return Optional.ofNullable(this.statistics);
    }
    /**
     * @return Field `threshold` has been removed from provider version 1.216.0. New field `escalations_critical.threshold` instead.
     * 
     */
    public Optional<String> threshold() {
        return Optional.ofNullable(this.threshold);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(AlarmCompositeExpressionExpressionList defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String comparisonOperator;
        private @Nullable String metricName;
        private @Nullable String period;
        private @Nullable String statistics;
        private @Nullable String threshold;
        public Builder() {}
        public Builder(AlarmCompositeExpressionExpressionList defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.comparisonOperator = defaults.comparisonOperator;
    	      this.metricName = defaults.metricName;
    	      this.period = defaults.period;
    	      this.statistics = defaults.statistics;
    	      this.threshold = defaults.threshold;
        }

        @CustomType.Setter
        public Builder comparisonOperator(@Nullable String comparisonOperator) {

            this.comparisonOperator = comparisonOperator;
            return this;
        }
        @CustomType.Setter
        public Builder metricName(@Nullable String metricName) {

            this.metricName = metricName;
            return this;
        }
        @CustomType.Setter
        public Builder period(@Nullable String period) {

            this.period = period;
            return this;
        }
        @CustomType.Setter
        public Builder statistics(@Nullable String statistics) {

            this.statistics = statistics;
            return this;
        }
        @CustomType.Setter
        public Builder threshold(@Nullable String threshold) {

            this.threshold = threshold;
            return this;
        }
        public AlarmCompositeExpressionExpressionList build() {
            final var _resultValue = new AlarmCompositeExpressionExpressionList();
            _resultValue.comparisonOperator = comparisonOperator;
            _resultValue.metricName = metricName;
            _resultValue.period = period;
            _resultValue.statistics = statistics;
            _resultValue.threshold = threshold;
            return _resultValue;
        }
    }
}
