// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * This data source provides the Vpc Nat Ips of the current Alibaba Cloud user.
 *
 * > **NOTE:** Available in v1.136.0+.
 *
 * ## Example Usage
 *
 * Basic Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as alicloud from "@pulumi/alicloud";
 *
 * const ids = alicloud.vpc.getNatIps({
 *     natGatewayId: "example_value",
 *     ids: [
 *         "example_value-1",
 *         "example_value-2",
 *     ],
 * });
 * export const vpcNatIpId1 = ids.then(ids => ids.ips[0].id);
 * const nameRegex = alicloud.vpc.getNatIps({
 *     natGatewayId: "example_value",
 *     nameRegex: "^my-NatIp",
 * });
 * export const vpcNatIpId2 = nameRegex.then(nameRegex => nameRegex.ips[0].id);
 * const natIpCidr = alicloud.vpc.getNatIps({
 *     natGatewayId: "example_value",
 *     natIpCidr: "example_value",
 *     nameRegex: "^my-NatIp",
 * });
 * export const vpcNatIpId3 = natIpCidr.then(natIpCidr => natIpCidr.ips[0].id);
 * const natIpName = alicloud.vpc.getNatIps({
 *     natGatewayId: "example_value",
 *     ids: ["example_value"],
 *     natIpNames: ["example_value"],
 * });
 * export const vpcNatIpId4 = natIpName.then(natIpName => natIpName.ips[0].id);
 * const natIpIds = alicloud.vpc.getNatIps({
 *     natGatewayId: "example_value",
 *     ids: ["example_value"],
 *     natIpIds: ["example_value"],
 * });
 * export const vpcNatIpId5 = natIpIds.then(natIpIds => natIpIds.ips[0].id);
 * const status = alicloud.vpc.getNatIps({
 *     natGatewayId: "example_value",
 *     ids: ["example_value"],
 *     status: "example_value",
 * });
 * export const vpcNatIpId6 = status.then(status => status.ips[0].id);
 * ```
 */
export function getNatIps(args: GetNatIpsArgs, opts?: pulumi.InvokeOptions): Promise<GetNatIpsResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("alicloud:vpc/getNatIps:getNatIps", {
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "natGatewayId": args.natGatewayId,
        "natIpCidr": args.natIpCidr,
        "natIpIds": args.natIpIds,
        "natIpNames": args.natIpNames,
        "outputFile": args.outputFile,
        "status": args.status,
    }, opts);
}

/**
 * A collection of arguments for invoking getNatIps.
 */
export interface GetNatIpsArgs {
    /**
     * A list of Nat Ip IDs.
     */
    readonly ids?: string[];
    /**
     * A regex string to filter results by Nat Ip name.
     */
    readonly nameRegex?: string;
    /**
     * The ID of the Virtual Private Cloud (VPC) NAT gateway to which the NAT IP address belongs.
     */
    readonly natGatewayId: string;
    /**
     * The CIDR block to which the NAT IP address belongs.
     */
    readonly natIpCidr?: string;
    readonly natIpIds?: string[];
    /**
     * The name of the NAT IP address.
     */
    readonly natIpNames?: string[];
    readonly outputFile?: string;
    /**
     * The status of the NAT IP address. Valid values: `Available`, `Deleting` and `Creating`.
     */
    readonly status?: string;
}

/**
 * A collection of values returned by getNatIps.
 */
export interface GetNatIpsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    readonly ips: outputs.vpc.GetNatIpsIp[];
    readonly nameRegex?: string;
    readonly names: string[];
    readonly natGatewayId: string;
    readonly natIpCidr?: string;
    readonly natIpIds?: string[];
    readonly natIpNames?: string[];
    readonly outputFile?: string;
    readonly status?: string;
}
