// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.clickhouseenterprisedbcluster.outputs;

import com.pulumi.alicloud.clickhouseenterprisedbcluster.outputs.ClickHouseEnterpriseDbClusterEndpointPort;
import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ClickHouseEnterpriseDbClusterEndpoint {
    /**
     * @return The computing group ID.
     * 
     */
    private @Nullable String computingGroupId;
    /**
     * @return The instance connection string.
     * 
     */
    private @Nullable String connectionString;
    /**
     * @return The endpoint name.
     * 
     */
    private @Nullable String endpointName;
    /**
     * @return The IP address.
     * 
     */
    private @Nullable String ipAddress;
    /**
     * @return The network type of the connection string.
     * 
     */
    private @Nullable String netType;
    /**
     * @return A list of port details.
     * 
     */
    private @Nullable List<ClickHouseEnterpriseDbClusterEndpointPort> ports;
    /**
     * @return The instance status.
     * 
     */
    private @Nullable String status;
    /**
     * @return The VPC ID.
     * 
     */
    private @Nullable String vpcId;
    /**
     * @return The VPC instance ID.
     * 
     */
    private @Nullable String vpcInstanceId;
    /**
     * @return vSwitch ID.
     * 
     */
    private @Nullable String vswitchId;

    private ClickHouseEnterpriseDbClusterEndpoint() {}
    /**
     * @return The computing group ID.
     * 
     */
    public Optional<String> computingGroupId() {
        return Optional.ofNullable(this.computingGroupId);
    }
    /**
     * @return The instance connection string.
     * 
     */
    public Optional<String> connectionString() {
        return Optional.ofNullable(this.connectionString);
    }
    /**
     * @return The endpoint name.
     * 
     */
    public Optional<String> endpointName() {
        return Optional.ofNullable(this.endpointName);
    }
    /**
     * @return The IP address.
     * 
     */
    public Optional<String> ipAddress() {
        return Optional.ofNullable(this.ipAddress);
    }
    /**
     * @return The network type of the connection string.
     * 
     */
    public Optional<String> netType() {
        return Optional.ofNullable(this.netType);
    }
    /**
     * @return A list of port details.
     * 
     */
    public List<ClickHouseEnterpriseDbClusterEndpointPort> ports() {
        return this.ports == null ? List.of() : this.ports;
    }
    /**
     * @return The instance status.
     * 
     */
    public Optional<String> status() {
        return Optional.ofNullable(this.status);
    }
    /**
     * @return The VPC ID.
     * 
     */
    public Optional<String> vpcId() {
        return Optional.ofNullable(this.vpcId);
    }
    /**
     * @return The VPC instance ID.
     * 
     */
    public Optional<String> vpcInstanceId() {
        return Optional.ofNullable(this.vpcInstanceId);
    }
    /**
     * @return vSwitch ID.
     * 
     */
    public Optional<String> vswitchId() {
        return Optional.ofNullable(this.vswitchId);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ClickHouseEnterpriseDbClusterEndpoint defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String computingGroupId;
        private @Nullable String connectionString;
        private @Nullable String endpointName;
        private @Nullable String ipAddress;
        private @Nullable String netType;
        private @Nullable List<ClickHouseEnterpriseDbClusterEndpointPort> ports;
        private @Nullable String status;
        private @Nullable String vpcId;
        private @Nullable String vpcInstanceId;
        private @Nullable String vswitchId;
        public Builder() {}
        public Builder(ClickHouseEnterpriseDbClusterEndpoint defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.computingGroupId = defaults.computingGroupId;
    	      this.connectionString = defaults.connectionString;
    	      this.endpointName = defaults.endpointName;
    	      this.ipAddress = defaults.ipAddress;
    	      this.netType = defaults.netType;
    	      this.ports = defaults.ports;
    	      this.status = defaults.status;
    	      this.vpcId = defaults.vpcId;
    	      this.vpcInstanceId = defaults.vpcInstanceId;
    	      this.vswitchId = defaults.vswitchId;
        }

        @CustomType.Setter
        public Builder computingGroupId(@Nullable String computingGroupId) {

            this.computingGroupId = computingGroupId;
            return this;
        }
        @CustomType.Setter
        public Builder connectionString(@Nullable String connectionString) {

            this.connectionString = connectionString;
            return this;
        }
        @CustomType.Setter
        public Builder endpointName(@Nullable String endpointName) {

            this.endpointName = endpointName;
            return this;
        }
        @CustomType.Setter
        public Builder ipAddress(@Nullable String ipAddress) {

            this.ipAddress = ipAddress;
            return this;
        }
        @CustomType.Setter
        public Builder netType(@Nullable String netType) {

            this.netType = netType;
            return this;
        }
        @CustomType.Setter
        public Builder ports(@Nullable List<ClickHouseEnterpriseDbClusterEndpointPort> ports) {

            this.ports = ports;
            return this;
        }
        public Builder ports(ClickHouseEnterpriseDbClusterEndpointPort... ports) {
            return ports(List.of(ports));
        }
        @CustomType.Setter
        public Builder status(@Nullable String status) {

            this.status = status;
            return this;
        }
        @CustomType.Setter
        public Builder vpcId(@Nullable String vpcId) {

            this.vpcId = vpcId;
            return this;
        }
        @CustomType.Setter
        public Builder vpcInstanceId(@Nullable String vpcInstanceId) {

            this.vpcInstanceId = vpcInstanceId;
            return this;
        }
        @CustomType.Setter
        public Builder vswitchId(@Nullable String vswitchId) {

            this.vswitchId = vswitchId;
            return this;
        }
        public ClickHouseEnterpriseDbClusterEndpoint build() {
            final var _resultValue = new ClickHouseEnterpriseDbClusterEndpoint();
            _resultValue.computingGroupId = computingGroupId;
            _resultValue.connectionString = connectionString;
            _resultValue.endpointName = endpointName;
            _resultValue.ipAddress = ipAddress;
            _resultValue.netType = netType;
            _resultValue.ports = ports;
            _resultValue.status = status;
            _resultValue.vpcId = vpcId;
            _resultValue.vpcInstanceId = vpcInstanceId;
            _resultValue.vswitchId = vswitchId;
            return _resultValue;
        }
    }
}
