// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.alicloud.privatelink.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetVpcEndpointServiceUsersUser {
    /**
     * @return The ID of the Vpc Endpoint Service User.
     * 
     */
    private String id;
    /**
     * @return The Id of Ram User.
     * 
     */
    private String userId;

    private GetVpcEndpointServiceUsersUser() {}
    /**
     * @return The ID of the Vpc Endpoint Service User.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return The Id of Ram User.
     * 
     */
    public String userId() {
        return this.userId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetVpcEndpointServiceUsersUser defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String userId;
        public Builder() {}
        public Builder(GetVpcEndpointServiceUsersUser defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.userId = defaults.userId;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetVpcEndpointServiceUsersUser", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder userId(String userId) {
            if (userId == null) {
              throw new MissingRequiredPropertyException("GetVpcEndpointServiceUsersUser", "userId");
            }
            this.userId = userId;
            return this;
        }
        public GetVpcEndpointServiceUsersUser build() {
            final var _resultValue = new GetVpcEndpointServiceUsersUser();
            _resultValue.id = id;
            _resultValue.userId = userId;
            return _resultValue;
        }
    }
}
