// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package dfs

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides the Apsara File Storage for HDFS Access Groups of the current Alibaba Cloud user.
//
// > **NOTE:** Available in v1.133.0+.
//
// ## Example Usage
//
// Basic Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-alicloud/sdk/v3/go/alicloud/dfs"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		ids, err := dfs.GetAccessGroups(ctx, &dfs.GetAccessGroupsArgs{
// 			Ids: []string{
// 				"example_id",
// 			},
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("dfsAccessGroupId1", ids.Groups[0].Id)
// 		opt0 := "^my-AccessGroup"
// 		nameRegex, err := dfs.GetAccessGroups(ctx, &dfs.GetAccessGroupsArgs{
// 			NameRegex: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("dfsAccessGroupId2", nameRegex.Groups[0].Id)
// 		return nil
// 	})
// }
// ```
func GetAccessGroups(ctx *pulumi.Context, args *GetAccessGroupsArgs, opts ...pulumi.InvokeOption) (*GetAccessGroupsResult, error) {
	var rv GetAccessGroupsResult
	err := ctx.Invoke("alicloud:dfs/getAccessGroups:getAccessGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccessGroups.
type GetAccessGroupsArgs struct {
	// A list of Access Group IDs.
	Ids   []string `pulumi:"ids"`
	Limit *int     `pulumi:"limit"`
	// A regex string to filter results by Access Group name.
	NameRegex   *string `pulumi:"nameRegex"`
	OrderBy     *string `pulumi:"orderBy"`
	OrderType   *string `pulumi:"orderType"`
	OutputFile  *string `pulumi:"outputFile"`
	StartOffset *int    `pulumi:"startOffset"`
}

// A collection of values returned by getAccessGroups.
type GetAccessGroupsResult struct {
	Groups []GetAccessGroupsGroup `pulumi:"groups"`
	// The provider-assigned unique ID for this managed resource.
	Id          string   `pulumi:"id"`
	Ids         []string `pulumi:"ids"`
	Limit       *int     `pulumi:"limit"`
	NameRegex   *string  `pulumi:"nameRegex"`
	Names       []string `pulumi:"names"`
	OrderBy     *string  `pulumi:"orderBy"`
	OrderType   *string  `pulumi:"orderType"`
	OutputFile  *string  `pulumi:"outputFile"`
	StartOffset *int     `pulumi:"startOffset"`
}
