// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package vpc

import (
	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// Provides a forward resource.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-alicloud/blob/master/website/docs/r/forward_entry.html.markdown.
type ForwardEntry struct {
	s *pulumi.ResourceState
}

// NewForwardEntry registers a new resource with the given unique name, arguments, and options.
func NewForwardEntry(ctx *pulumi.Context,
	name string, args *ForwardEntryArgs, opts ...pulumi.ResourceOpt) (*ForwardEntry, error) {
	if args == nil || args.ExternalIp == nil {
		return nil, errors.New("missing required argument 'ExternalIp'")
	}
	if args == nil || args.ExternalPort == nil {
		return nil, errors.New("missing required argument 'ExternalPort'")
	}
	if args == nil || args.ForwardTableId == nil {
		return nil, errors.New("missing required argument 'ForwardTableId'")
	}
	if args == nil || args.InternalIp == nil {
		return nil, errors.New("missing required argument 'InternalIp'")
	}
	if args == nil || args.InternalPort == nil {
		return nil, errors.New("missing required argument 'InternalPort'")
	}
	if args == nil || args.IpProtocol == nil {
		return nil, errors.New("missing required argument 'IpProtocol'")
	}
	inputs := make(map[string]interface{})
	if args == nil {
		inputs["externalIp"] = nil
		inputs["externalPort"] = nil
		inputs["forwardTableId"] = nil
		inputs["internalIp"] = nil
		inputs["internalPort"] = nil
		inputs["ipProtocol"] = nil
		inputs["name"] = nil
	} else {
		inputs["externalIp"] = args.ExternalIp
		inputs["externalPort"] = args.ExternalPort
		inputs["forwardTableId"] = args.ForwardTableId
		inputs["internalIp"] = args.InternalIp
		inputs["internalPort"] = args.InternalPort
		inputs["ipProtocol"] = args.IpProtocol
		inputs["name"] = args.Name
	}
	inputs["forwardEntryId"] = nil
	s, err := ctx.RegisterResource("alicloud:vpc/forwardEntry:ForwardEntry", name, true, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &ForwardEntry{s: s}, nil
}

// GetForwardEntry gets an existing ForwardEntry resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetForwardEntry(ctx *pulumi.Context,
	name string, id pulumi.ID, state *ForwardEntryState, opts ...pulumi.ResourceOpt) (*ForwardEntry, error) {
	inputs := make(map[string]interface{})
	if state != nil {
		inputs["externalIp"] = state.ExternalIp
		inputs["externalPort"] = state.ExternalPort
		inputs["forwardEntryId"] = state.ForwardEntryId
		inputs["forwardTableId"] = state.ForwardTableId
		inputs["internalIp"] = state.InternalIp
		inputs["internalPort"] = state.InternalPort
		inputs["ipProtocol"] = state.IpProtocol
		inputs["name"] = state.Name
	}
	s, err := ctx.ReadResource("alicloud:vpc/forwardEntry:ForwardEntry", name, id, inputs, opts...)
	if err != nil {
		return nil, err
	}
	return &ForwardEntry{s: s}, nil
}

// URN is this resource's unique name assigned by Pulumi.
func (r *ForwardEntry) URN() pulumi.URNOutput {
	return r.s.URN()
}

// ID is this resource's unique identifier assigned by its provider.
func (r *ForwardEntry) ID() pulumi.IDOutput {
	return r.s.ID()
}

// The external ip address, the ip must along bandwidth package public ip which `vpc.NatGateway` argument `bandwidthPackages`.
func (r *ForwardEntry) ExternalIp() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["externalIp"])
}

// The external port, valid value is 1~65535|any.
func (r *ForwardEntry) ExternalPort() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["externalPort"])
}

// The id of the forward entry on the server.
func (r *ForwardEntry) ForwardEntryId() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["forwardEntryId"])
}

// The value can get from `vpc.NatGateway` Attributes "forwardTableIds".
func (r *ForwardEntry) ForwardTableId() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["forwardTableId"])
}

// The internal ip, must a private ip.
func (r *ForwardEntry) InternalIp() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["internalIp"])
}

// The internal port, valid value is 1~65535|any.
func (r *ForwardEntry) InternalPort() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["internalPort"])
}

// The ip protocal, valid value is tcp|udp|any.
func (r *ForwardEntry) IpProtocol() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["ipProtocol"])
}

// The name of forward entry.
func (r *ForwardEntry) Name() pulumi.StringOutput {
	return (pulumi.StringOutput)(r.s.State["name"])
}

// Input properties used for looking up and filtering ForwardEntry resources.
type ForwardEntryState struct {
	// The external ip address, the ip must along bandwidth package public ip which `vpc.NatGateway` argument `bandwidthPackages`.
	ExternalIp interface{}
	// The external port, valid value is 1~65535|any.
	ExternalPort interface{}
	// The id of the forward entry on the server.
	ForwardEntryId interface{}
	// The value can get from `vpc.NatGateway` Attributes "forwardTableIds".
	ForwardTableId interface{}
	// The internal ip, must a private ip.
	InternalIp interface{}
	// The internal port, valid value is 1~65535|any.
	InternalPort interface{}
	// The ip protocal, valid value is tcp|udp|any.
	IpProtocol interface{}
	// The name of forward entry.
	Name interface{}
}

// The set of arguments for constructing a ForwardEntry resource.
type ForwardEntryArgs struct {
	// The external ip address, the ip must along bandwidth package public ip which `vpc.NatGateway` argument `bandwidthPackages`.
	ExternalIp interface{}
	// The external port, valid value is 1~65535|any.
	ExternalPort interface{}
	// The value can get from `vpc.NatGateway` Attributes "forwardTableIds".
	ForwardTableId interface{}
	// The internal ip, must a private ip.
	InternalIp interface{}
	// The internal port, valid value is 1~65535|any.
	InternalPort interface{}
	// The ip protocal, valid value is tcp|udp|any.
	IpProtocol interface{}
	// The name of forward entry.
	Name interface{}
}
