// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AliCloud.Slb.Inputs
{

    public sealed class ServerGroupServerGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("port", required: true)]
        public Input<int> Port { get; set; } = null!;

        [Input("serverIds", required: true)]
        private InputList<string>? _serverIds;
        public InputList<string> ServerIds
        {
            get => _serverIds ?? (_serverIds = new InputList<string>());
            set => _serverIds = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public ServerGroupServerGetArgs()
        {
        }
        public static new ServerGroupServerGetArgs Empty => new ServerGroupServerGetArgs();
    }
}
